# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: anqi.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='anqi.proto',
  package='DataConfig',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\nanqi.proto\x12\nDataConfig\"]\n\x07\x41nqiCfg\x12\x11\n\x06\x63\x66g_id\x18\x01 \x02(\r:\x01\x30\x12\x14\n\tanqi_type\x18\x02 \x01(\r:\x01\x30\x12\x13\n\x08skill_id\x18\x03 \x01(\r:\x01\x30\x12\x14\n\tuse_times\x18\x04 \x01(\r:\x01\x30\"3\n\rAnqiCfg_ARRAY\x12\"\n\x05items\x18\x01 \x03(\x0b\x32\x13.DataConfig.AnqiCfg')
)




_ANQICFG = _descriptor.Descriptor(
  name='AnqiCfg',
  full_name='DataConfig.AnqiCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cfg_id', full_name='DataConfig.AnqiCfg.cfg_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='anqi_type', full_name='DataConfig.AnqiCfg.anqi_type', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='skill_id', full_name='DataConfig.AnqiCfg.skill_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_times', full_name='DataConfig.AnqiCfg.use_times', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=119,
)


_ANQICFG_ARRAY = _descriptor.Descriptor(
  name='AnqiCfg_ARRAY',
  full_name='DataConfig.AnqiCfg_ARRAY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='DataConfig.AnqiCfg_ARRAY.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=172,
)

_ANQICFG_ARRAY.fields_by_name['items'].message_type = _ANQICFG
DESCRIPTOR.message_types_by_name['AnqiCfg'] = _ANQICFG
DESCRIPTOR.message_types_by_name['AnqiCfg_ARRAY'] = _ANQICFG_ARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnqiCfg = _reflection.GeneratedProtocolMessageType('AnqiCfg', (_message.Message,), {
  'DESCRIPTOR' : _ANQICFG,
  '__module__' : 'anqi_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.AnqiCfg)
  })
_sym_db.RegisterMessage(AnqiCfg)

AnqiCfg_ARRAY = _reflection.GeneratedProtocolMessageType('AnqiCfg_ARRAY', (_message.Message,), {
  'DESCRIPTOR' : _ANQICFG_ARRAY,
  '__module__' : 'anqi_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.AnqiCfg_ARRAY)
  })
_sym_db.RegisterMessage(AnqiCfg_ARRAY)


# @@protoc_insertion_point(module_scope)
