# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: battleflowui.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='battleflowui.proto',
  package='DataConfig',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x12\x62\x61ttleflowui.proto\x12\nDataConfig\"\xaa\x02\n\x0f\x42\x61ttleFlowUICfg\x12\x11\n\x06\x63\x66g_id\x18\x01 \x02(\r:\x01\x30\x12\x0e\n\x04\x64\x65sc\x18\x02 \x01(\t:\x00\x12\x12\n\x07type_id\x18\x03 \x02(\r:\x01\x30\x12\x16\n\x0bsecond_type\x18\x04 \x02(\r:\x01\x30\x12\x12\n\x08\x66\x61r_dist\x18\x05 \x01(\t:\x00\x12\x13\n\tnear_dist\x18\x06 \x01(\t:\x00\x12\x14\n\tintensity\x18\x07 \x01(\r:\x01\x30\x12\x0f\n\x04read\x18\x08 \x01(\r:\x01\x30\x12\x13\n\x08readtime\x18\t \x01(\x02:\x01\x30\x12\x0e\n\x04\x64isc\x18\n \x01(\t:\x00\x12\x14\n\nforbiddisc\x18\x0b \x01(\t:\x00\x12\x13\n\x08offset_x\x18\x0c \x01(\x02:\x01\x30\x12\x13\n\x08offset_y\x18\r \x01(\x02:\x01\x30\x12\x13\n\x08offset_z\x18\x0e \x01(\x02:\x01\x30\"C\n\x15\x42\x61ttleFlowUICfg_ARRAY\x12*\n\x05items\x18\x01 \x03(\x0b\x32\x1b.DataConfig.BattleFlowUICfg')
)




_BATTLEFLOWUICFG = _descriptor.Descriptor(
  name='BattleFlowUICfg',
  full_name='DataConfig.BattleFlowUICfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cfg_id', full_name='DataConfig.BattleFlowUICfg.cfg_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='desc', full_name='DataConfig.BattleFlowUICfg.desc', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type_id', full_name='DataConfig.BattleFlowUICfg.type_id', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='second_type', full_name='DataConfig.BattleFlowUICfg.second_type', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='far_dist', full_name='DataConfig.BattleFlowUICfg.far_dist', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='near_dist', full_name='DataConfig.BattleFlowUICfg.near_dist', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='intensity', full_name='DataConfig.BattleFlowUICfg.intensity', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='read', full_name='DataConfig.BattleFlowUICfg.read', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='readtime', full_name='DataConfig.BattleFlowUICfg.readtime', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disc', full_name='DataConfig.BattleFlowUICfg.disc', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='forbiddisc', full_name='DataConfig.BattleFlowUICfg.forbiddisc', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset_x', full_name='DataConfig.BattleFlowUICfg.offset_x', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset_y', full_name='DataConfig.BattleFlowUICfg.offset_y', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset_z', full_name='DataConfig.BattleFlowUICfg.offset_z', index=13,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=333,
)


_BATTLEFLOWUICFG_ARRAY = _descriptor.Descriptor(
  name='BattleFlowUICfg_ARRAY',
  full_name='DataConfig.BattleFlowUICfg_ARRAY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='DataConfig.BattleFlowUICfg_ARRAY.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=402,
)

_BATTLEFLOWUICFG_ARRAY.fields_by_name['items'].message_type = _BATTLEFLOWUICFG
DESCRIPTOR.message_types_by_name['BattleFlowUICfg'] = _BATTLEFLOWUICFG
DESCRIPTOR.message_types_by_name['BattleFlowUICfg_ARRAY'] = _BATTLEFLOWUICFG_ARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BattleFlowUICfg = _reflection.GeneratedProtocolMessageType('BattleFlowUICfg', (_message.Message,), {
  'DESCRIPTOR' : _BATTLEFLOWUICFG,
  '__module__' : 'battleflowui_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.BattleFlowUICfg)
  })
_sym_db.RegisterMessage(BattleFlowUICfg)

BattleFlowUICfg_ARRAY = _reflection.GeneratedProtocolMessageType('BattleFlowUICfg_ARRAY', (_message.Message,), {
  'DESCRIPTOR' : _BATTLEFLOWUICFG_ARRAY,
  '__module__' : 'battleflowui_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.BattleFlowUICfg_ARRAY)
  })
_sym_db.RegisterMessage(BattleFlowUICfg_ARRAY)


# @@protoc_insertion_point(module_scope)
