# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hero.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hero.proto',
  package='DataConfig',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\nhero.proto\x12\nDataConfig\"\x8a\x01\n\x07HeroCfg\x12\x11\n\x06\x63\x66g_id\x18\x01 \x02(\r:\x01\x30\x12\x13\n\thero_name\x18\x02 \x02(\t:\x00\x12\x12\n\x07skin_id\x18\x03 \x02(\r:\x01\x30\x12\x15\n\rskill_id_list\x18\x04 \x03(\r\x12\x11\n\tattr_list\x18\x05 \x03(\r\x12\x19\n\x0fmove_controller\x18\x06 \x02(\t:\x00\"3\n\rHeroCfg_ARRAY\x12\"\n\x05items\x18\x01 \x03(\x0b\x32\x13.DataConfig.HeroCfg')
)




_HEROCFG = _descriptor.Descriptor(
  name='HeroCfg',
  full_name='DataConfig.HeroCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cfg_id', full_name='DataConfig.HeroCfg.cfg_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hero_name', full_name='DataConfig.HeroCfg.hero_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='skin_id', full_name='DataConfig.HeroCfg.skin_id', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='skill_id_list', full_name='DataConfig.HeroCfg.skill_id_list', index=3,
      number=4, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attr_list', full_name='DataConfig.HeroCfg.attr_list', index=4,
      number=5, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='move_controller', full_name='DataConfig.HeroCfg.move_controller', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=165,
)


_HEROCFG_ARRAY = _descriptor.Descriptor(
  name='HeroCfg_ARRAY',
  full_name='DataConfig.HeroCfg_ARRAY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='DataConfig.HeroCfg_ARRAY.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=218,
)

_HEROCFG_ARRAY.fields_by_name['items'].message_type = _HEROCFG
DESCRIPTOR.message_types_by_name['HeroCfg'] = _HEROCFG
DESCRIPTOR.message_types_by_name['HeroCfg_ARRAY'] = _HEROCFG_ARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HeroCfg = _reflection.GeneratedProtocolMessageType('HeroCfg', (_message.Message,), {
  'DESCRIPTOR' : _HEROCFG,
  '__module__' : 'hero_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.HeroCfg)
  })
_sym_db.RegisterMessage(HeroCfg)

HeroCfg_ARRAY = _reflection.GeneratedProtocolMessageType('HeroCfg_ARRAY', (_message.Message,), {
  'DESCRIPTOR' : _HEROCFG_ARRAY,
  '__module__' : 'hero_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.HeroCfg_ARRAY)
  })
_sym_db.RegisterMessage(HeroCfg_ARRAY)


# @@protoc_insertion_point(module_scope)
