# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ladder.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ladder.proto',
  package='DataConfig',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0cladder.proto\x12\nDataConfig\"\x8e\x02\n\tLadderCfg\x12\x11\n\x06\x63\x66g_id\x18\x01 \x02(\r:\x01\x30\x12\x0e\n\x04name\x18\x02 \x02(\t:\x00\x12\x13\n\x08model_id\x18\x03 \x01(\r:\x01\x30\x12\x16\n\x0b\x65nter_state\x18\x04 \x01(\r:\x01\x30\x12\x19\n\x0eself_animation\x18\x05 \x01(\r:\x01\x30\x12\r\n\x02\x63\x64\x18\x06 \x01(\x02:\x01\x30\x12\x15\n\nexit_state\x18\x07 \x01(\r:\x01\x30\x12\x15\n\nkeep_state\x18\x08 \x01(\r:\x01\x30\x12$\n\x15\x64isable_in_guard_view\x18\t \x01(\x08:\x05\x66\x61lse\x12\x16\n\x0b\x65nergy_cost\x18\n \x01(\x02:\x01\x30\x12\x1b\n\x10max_player_count\x18\x0b \x01(\r:\x01\x30\"7\n\x0fLadderCfg_ARRAY\x12$\n\x05items\x18\x01 \x03(\x0b\x32\x15.DataConfig.LadderCfg')
)




_LADDERCFG = _descriptor.Descriptor(
  name='LadderCfg',
  full_name='DataConfig.LadderCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cfg_id', full_name='DataConfig.LadderCfg.cfg_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='DataConfig.LadderCfg.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_id', full_name='DataConfig.LadderCfg.model_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enter_state', full_name='DataConfig.LadderCfg.enter_state', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='self_animation', full_name='DataConfig.LadderCfg.self_animation', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cd', full_name='DataConfig.LadderCfg.cd', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exit_state', full_name='DataConfig.LadderCfg.exit_state', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keep_state', full_name='DataConfig.LadderCfg.keep_state', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disable_in_guard_view', full_name='DataConfig.LadderCfg.disable_in_guard_view', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='energy_cost', full_name='DataConfig.LadderCfg.energy_cost', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_player_count', full_name='DataConfig.LadderCfg.max_player_count', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=299,
)


_LADDERCFG_ARRAY = _descriptor.Descriptor(
  name='LadderCfg_ARRAY',
  full_name='DataConfig.LadderCfg_ARRAY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='DataConfig.LadderCfg_ARRAY.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=356,
)

_LADDERCFG_ARRAY.fields_by_name['items'].message_type = _LADDERCFG
DESCRIPTOR.message_types_by_name['LadderCfg'] = _LADDERCFG
DESCRIPTOR.message_types_by_name['LadderCfg_ARRAY'] = _LADDERCFG_ARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LadderCfg = _reflection.GeneratedProtocolMessageType('LadderCfg', (_message.Message,), {
  'DESCRIPTOR' : _LADDERCFG,
  '__module__' : 'ladder_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.LadderCfg)
  })
_sym_db.RegisterMessage(LadderCfg)

LadderCfg_ARRAY = _reflection.GeneratedProtocolMessageType('LadderCfg_ARRAY', (_message.Message,), {
  'DESCRIPTOR' : _LADDERCFG_ARRAY,
  '__module__' : 'ladder_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.LadderCfg_ARRAY)
  })
_sym_db.RegisterMessage(LadderCfg_ARRAY)


# @@protoc_insertion_point(module_scope)
