# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='search.proto',
  package='DataConfig',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0csearch.proto\x12\nDataConfig\"\xea\x01\n\tSearchCfg\x12\x11\n\x06\x63\x66g_id\x18\x01 \x02(\r:\x01\x30\x12\x14\n\nactor_type\x18\x02 \x01(\t:\x00\x12\x1a\n\x0b\x66ilter_self\x18\x03 \x02(\x08:\x05\x66\x61lse\x12\x14\n\tsort_type\x18\x04 \x02(\x05:\x01\x30\x12\x16\n\x0bsearch_type\x18\x05 \x02(\x05:\x01\x30\x12\x14\n\nsearch_dis\x18\x06 \x02(\t:\x00\x12\x1a\n\x10target_sub_state\x18\x07 \x01(\t:\x00\x12\x14\n\tnum_limit\x18\x08 \x01(\x05:\x01\x30\x12\x10\n\x06\x65nergy\x18\t \x01(\t:\x00\x12\x10\n\x06\x65xpose\x18\n \x01(\t:\x00\"7\n\x0fSearchCfg_ARRAY\x12$\n\x05items\x18\x01 \x03(\x0b\x32\x15.DataConfig.SearchCfg')
)




_SEARCHCFG = _descriptor.Descriptor(
  name='SearchCfg',
  full_name='DataConfig.SearchCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cfg_id', full_name='DataConfig.SearchCfg.cfg_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actor_type', full_name='DataConfig.SearchCfg.actor_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filter_self', full_name='DataConfig.SearchCfg.filter_self', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sort_type', full_name='DataConfig.SearchCfg.sort_type', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='search_type', full_name='DataConfig.SearchCfg.search_type', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='search_dis', full_name='DataConfig.SearchCfg.search_dis', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_sub_state', full_name='DataConfig.SearchCfg.target_sub_state', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_limit', full_name='DataConfig.SearchCfg.num_limit', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='energy', full_name='DataConfig.SearchCfg.energy', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expose', full_name='DataConfig.SearchCfg.expose', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=263,
)


_SEARCHCFG_ARRAY = _descriptor.Descriptor(
  name='SearchCfg_ARRAY',
  full_name='DataConfig.SearchCfg_ARRAY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='DataConfig.SearchCfg_ARRAY.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=265,
  serialized_end=320,
)

_SEARCHCFG_ARRAY.fields_by_name['items'].message_type = _SEARCHCFG
DESCRIPTOR.message_types_by_name['SearchCfg'] = _SEARCHCFG
DESCRIPTOR.message_types_by_name['SearchCfg_ARRAY'] = _SEARCHCFG_ARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SearchCfg = _reflection.GeneratedProtocolMessageType('SearchCfg', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHCFG,
  '__module__' : 'search_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.SearchCfg)
  })
_sym_db.RegisterMessage(SearchCfg)

SearchCfg_ARRAY = _reflection.GeneratedProtocolMessageType('SearchCfg_ARRAY', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHCFG_ARRAY,
  '__module__' : 'search_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.SearchCfg_ARRAY)
  })
_sym_db.RegisterMessage(SearchCfg_ARRAY)


# @@protoc_insertion_point(module_scope)
