# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: skin.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='skin.proto',
  package='DataConfig',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\nskin.proto\x12\nDataConfig\"o\n\x07SkinCfg\x12\x11\n\x06\x63\x66g_id\x18\x01 \x02(\r:\x01\x30\x12\x14\n\nskill_name\x18\x02 \x02(\t:\x00\x12\x14\n\nskill_desc\x18\x03 \x02(\t:\x00\x12\x13\n\x08model_id\x18\x04 \x02(\r:\x01\x30\x12\x10\n\x05price\x18\x05 \x02(\x05:\x01\x30\"3\n\rSkinCfg_ARRAY\x12\"\n\x05items\x18\x01 \x03(\x0b\x32\x13.DataConfig.SkinCfg')
)




_SKINCFG = _descriptor.Descriptor(
  name='SkinCfg',
  full_name='DataConfig.SkinCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cfg_id', full_name='DataConfig.SkinCfg.cfg_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='skill_name', full_name='DataConfig.SkinCfg.skill_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='skill_desc', full_name='DataConfig.SkinCfg.skill_desc', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_id', full_name='DataConfig.SkinCfg.model_id', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='DataConfig.SkinCfg.price', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=137,
)


_SKINCFG_ARRAY = _descriptor.Descriptor(
  name='SkinCfg_ARRAY',
  full_name='DataConfig.SkinCfg_ARRAY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='DataConfig.SkinCfg_ARRAY.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=190,
)

_SKINCFG_ARRAY.fields_by_name['items'].message_type = _SKINCFG
DESCRIPTOR.message_types_by_name['SkinCfg'] = _SKINCFG
DESCRIPTOR.message_types_by_name['SkinCfg_ARRAY'] = _SKINCFG_ARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SkinCfg = _reflection.GeneratedProtocolMessageType('SkinCfg', (_message.Message,), {
  'DESCRIPTOR' : _SKINCFG,
  '__module__' : 'skin_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.SkinCfg)
  })
_sym_db.RegisterMessage(SkinCfg)

SkinCfg_ARRAY = _reflection.GeneratedProtocolMessageType('SkinCfg_ARRAY', (_message.Message,), {
  'DESCRIPTOR' : _SKINCFG_ARRAY,
  '__module__' : 'skin_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.SkinCfg_ARRAY)
  })
_sym_db.RegisterMessage(SkinCfg_ARRAY)


# @@protoc_insertion_point(module_scope)
