# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: specialbag.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='specialbag.proto',
  package='DataConfig',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x10specialbag.proto\x12\nDataConfig\"2\n\rSpecialBagCfg\x12\x11\n\x06\x63\x66g_id\x18\x01 \x02(\r:\x01\x30\x12\x0e\n\x03num\x18\x02 \x01(\r:\x01\x30\"?\n\x13SpecialBagCfg_ARRAY\x12(\n\x05items\x18\x01 \x03(\x0b\x32\x19.DataConfig.SpecialBagCfg')
)




_SPECIALBAGCFG = _descriptor.Descriptor(
  name='SpecialBagCfg',
  full_name='DataConfig.SpecialBagCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cfg_id', full_name='DataConfig.SpecialBagCfg.cfg_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num', full_name='DataConfig.SpecialBagCfg.num', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=82,
)


_SPECIALBAGCFG_ARRAY = _descriptor.Descriptor(
  name='SpecialBagCfg_ARRAY',
  full_name='DataConfig.SpecialBagCfg_ARRAY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='DataConfig.SpecialBagCfg_ARRAY.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=147,
)

_SPECIALBAGCFG_ARRAY.fields_by_name['items'].message_type = _SPECIALBAGCFG
DESCRIPTOR.message_types_by_name['SpecialBagCfg'] = _SPECIALBAGCFG
DESCRIPTOR.message_types_by_name['SpecialBagCfg_ARRAY'] = _SPECIALBAGCFG_ARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SpecialBagCfg = _reflection.GeneratedProtocolMessageType('SpecialBagCfg', (_message.Message,), {
  'DESCRIPTOR' : _SPECIALBAGCFG,
  '__module__' : 'specialbag_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.SpecialBagCfg)
  })
_sym_db.RegisterMessage(SpecialBagCfg)

SpecialBagCfg_ARRAY = _reflection.GeneratedProtocolMessageType('SpecialBagCfg_ARRAY', (_message.Message,), {
  'DESCRIPTOR' : _SPECIALBAGCFG_ARRAY,
  '__module__' : 'specialbag_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.SpecialBagCfg_ARRAY)
  })
_sym_db.RegisterMessage(SpecialBagCfg_ARRAY)


# @@protoc_insertion_point(module_scope)
