# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: anqi.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='anqi.proto',
  package='DataConfig',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nanqi.proto\x12\nDataConfig\"m\n\x07\x41nqiCfg\x12\x13\n\x06\x63\x66g_id\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x16\n\tanqi_type\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x12\n\x05param\x18\x03 \x01(\rH\x02\x88\x01\x01\x42\t\n\x07_cfg_idB\x0c\n\n_anqi_typeB\x08\n\x06_param\"\x8c\x01\n\x0c\x41nqiCfgSheet\x12\x37\n\x08item_dic\x18\x01 \x03(\x0b\x32%.DataConfig.AnqiCfgSheet.ItemDicEntry\x1a\x43\n\x0cItemDicEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.DataConfig.AnqiCfg:\x02\x38\x01\x62\x06proto3'
)




_ANQICFG = _descriptor.Descriptor(
  name='AnqiCfg',
  full_name='DataConfig.AnqiCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cfg_id', full_name='DataConfig.AnqiCfg.cfg_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='anqi_type', full_name='DataConfig.AnqiCfg.anqi_type', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='param', full_name='DataConfig.AnqiCfg.param', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_cfg_id', full_name='DataConfig.AnqiCfg._cfg_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_anqi_type', full_name='DataConfig.AnqiCfg._anqi_type',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_param', full_name='DataConfig.AnqiCfg._param',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=26,
  serialized_end=135,
)


_ANQICFGSHEET_ITEMDICENTRY = _descriptor.Descriptor(
  name='ItemDicEntry',
  full_name='DataConfig.AnqiCfgSheet.ItemDicEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DataConfig.AnqiCfgSheet.ItemDicEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='DataConfig.AnqiCfgSheet.ItemDicEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=278,
)

_ANQICFGSHEET = _descriptor.Descriptor(
  name='AnqiCfgSheet',
  full_name='DataConfig.AnqiCfgSheet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_dic', full_name='DataConfig.AnqiCfgSheet.item_dic', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ANQICFGSHEET_ITEMDICENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=278,
)

_ANQICFG.oneofs_by_name['_cfg_id'].fields.append(
  _ANQICFG.fields_by_name['cfg_id'])
_ANQICFG.fields_by_name['cfg_id'].containing_oneof = _ANQICFG.oneofs_by_name['_cfg_id']
_ANQICFG.oneofs_by_name['_anqi_type'].fields.append(
  _ANQICFG.fields_by_name['anqi_type'])
_ANQICFG.fields_by_name['anqi_type'].containing_oneof = _ANQICFG.oneofs_by_name['_anqi_type']
_ANQICFG.oneofs_by_name['_param'].fields.append(
  _ANQICFG.fields_by_name['param'])
_ANQICFG.fields_by_name['param'].containing_oneof = _ANQICFG.oneofs_by_name['_param']
_ANQICFGSHEET_ITEMDICENTRY.fields_by_name['value'].message_type = _ANQICFG
_ANQICFGSHEET_ITEMDICENTRY.containing_type = _ANQICFGSHEET
_ANQICFGSHEET.fields_by_name['item_dic'].message_type = _ANQICFGSHEET_ITEMDICENTRY
DESCRIPTOR.message_types_by_name['AnqiCfg'] = _ANQICFG
DESCRIPTOR.message_types_by_name['AnqiCfgSheet'] = _ANQICFGSHEET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnqiCfg = _reflection.GeneratedProtocolMessageType('AnqiCfg', (_message.Message,), {
  'DESCRIPTOR' : _ANQICFG,
  '__module__' : 'anqi_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.AnqiCfg)
  })
_sym_db.RegisterMessage(AnqiCfg)

AnqiCfgSheet = _reflection.GeneratedProtocolMessageType('AnqiCfgSheet', (_message.Message,), {

  'ItemDicEntry' : _reflection.GeneratedProtocolMessageType('ItemDicEntry', (_message.Message,), {
    'DESCRIPTOR' : _ANQICFGSHEET_ITEMDICENTRY,
    '__module__' : 'anqi_pb2'
    # @@protoc_insertion_point(class_scope:DataConfig.AnqiCfgSheet.ItemDicEntry)
    })
  ,
  'DESCRIPTOR' : _ANQICFGSHEET,
  '__module__' : 'anqi_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.AnqiCfgSheet)
  })
_sym_db.RegisterMessage(AnqiCfgSheet)
_sym_db.RegisterMessage(AnqiCfgSheet.ItemDicEntry)


_ANQICFGSHEET_ITEMDICENTRY._options = None
# @@protoc_insertion_point(module_scope)
