# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: architectureproperty.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='architectureproperty.proto',
  package='DataConfig',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1a\x61rchitectureproperty.proto\x12\nDataConfig\"q\n\x17\x41rchitecturePropertyCfg\x12\x13\n\x06\x63\x66g_id\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x11\n\x04name\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x11\n\x04note\x18\x03 \x01(\tH\x02\x88\x01\x01\x42\t\n\x07_cfg_idB\x07\n\x05_nameB\x07\n\x05_note\"\xbc\x01\n\x1c\x41rchitecturePropertyCfgSheet\x12G\n\x08item_dic\x18\x01 \x03(\x0b\x32\x35.DataConfig.ArchitecturePropertyCfgSheet.ItemDicEntry\x1aS\n\x0cItemDicEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x32\n\x05value\x18\x02 \x01(\x0b\x32#.DataConfig.ArchitecturePropertyCfg:\x02\x38\x01\x62\x06proto3'
)




_ARCHITECTUREPROPERTYCFG = _descriptor.Descriptor(
  name='ArchitecturePropertyCfg',
  full_name='DataConfig.ArchitecturePropertyCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cfg_id', full_name='DataConfig.ArchitecturePropertyCfg.cfg_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='DataConfig.ArchitecturePropertyCfg.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='note', full_name='DataConfig.ArchitecturePropertyCfg.note', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_cfg_id', full_name='DataConfig.ArchitecturePropertyCfg._cfg_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_name', full_name='DataConfig.ArchitecturePropertyCfg._name',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_note', full_name='DataConfig.ArchitecturePropertyCfg._note',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=42,
  serialized_end=155,
)


_ARCHITECTUREPROPERTYCFGSHEET_ITEMDICENTRY = _descriptor.Descriptor(
  name='ItemDicEntry',
  full_name='DataConfig.ArchitecturePropertyCfgSheet.ItemDicEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DataConfig.ArchitecturePropertyCfgSheet.ItemDicEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='DataConfig.ArchitecturePropertyCfgSheet.ItemDicEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=346,
)

_ARCHITECTUREPROPERTYCFGSHEET = _descriptor.Descriptor(
  name='ArchitecturePropertyCfgSheet',
  full_name='DataConfig.ArchitecturePropertyCfgSheet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_dic', full_name='DataConfig.ArchitecturePropertyCfgSheet.item_dic', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ARCHITECTUREPROPERTYCFGSHEET_ITEMDICENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=346,
)

_ARCHITECTUREPROPERTYCFG.oneofs_by_name['_cfg_id'].fields.append(
  _ARCHITECTUREPROPERTYCFG.fields_by_name['cfg_id'])
_ARCHITECTUREPROPERTYCFG.fields_by_name['cfg_id'].containing_oneof = _ARCHITECTUREPROPERTYCFG.oneofs_by_name['_cfg_id']
_ARCHITECTUREPROPERTYCFG.oneofs_by_name['_name'].fields.append(
  _ARCHITECTUREPROPERTYCFG.fields_by_name['name'])
_ARCHITECTUREPROPERTYCFG.fields_by_name['name'].containing_oneof = _ARCHITECTUREPROPERTYCFG.oneofs_by_name['_name']
_ARCHITECTUREPROPERTYCFG.oneofs_by_name['_note'].fields.append(
  _ARCHITECTUREPROPERTYCFG.fields_by_name['note'])
_ARCHITECTUREPROPERTYCFG.fields_by_name['note'].containing_oneof = _ARCHITECTUREPROPERTYCFG.oneofs_by_name['_note']
_ARCHITECTUREPROPERTYCFGSHEET_ITEMDICENTRY.fields_by_name['value'].message_type = _ARCHITECTUREPROPERTYCFG
_ARCHITECTUREPROPERTYCFGSHEET_ITEMDICENTRY.containing_type = _ARCHITECTUREPROPERTYCFGSHEET
_ARCHITECTUREPROPERTYCFGSHEET.fields_by_name['item_dic'].message_type = _ARCHITECTUREPROPERTYCFGSHEET_ITEMDICENTRY
DESCRIPTOR.message_types_by_name['ArchitecturePropertyCfg'] = _ARCHITECTUREPROPERTYCFG
DESCRIPTOR.message_types_by_name['ArchitecturePropertyCfgSheet'] = _ARCHITECTUREPROPERTYCFGSHEET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ArchitecturePropertyCfg = _reflection.GeneratedProtocolMessageType('ArchitecturePropertyCfg', (_message.Message,), {
  'DESCRIPTOR' : _ARCHITECTUREPROPERTYCFG,
  '__module__' : 'architectureproperty_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.ArchitecturePropertyCfg)
  })
_sym_db.RegisterMessage(ArchitecturePropertyCfg)

ArchitecturePropertyCfgSheet = _reflection.GeneratedProtocolMessageType('ArchitecturePropertyCfgSheet', (_message.Message,), {

  'ItemDicEntry' : _reflection.GeneratedProtocolMessageType('ItemDicEntry', (_message.Message,), {
    'DESCRIPTOR' : _ARCHITECTUREPROPERTYCFGSHEET_ITEMDICENTRY,
    '__module__' : 'architectureproperty_pb2'
    # @@protoc_insertion_point(class_scope:DataConfig.ArchitecturePropertyCfgSheet.ItemDicEntry)
    })
  ,
  'DESCRIPTOR' : _ARCHITECTUREPROPERTYCFGSHEET,
  '__module__' : 'architectureproperty_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.ArchitecturePropertyCfgSheet)
  })
_sym_db.RegisterMessage(ArchitecturePropertyCfgSheet)
_sym_db.RegisterMessage(ArchitecturePropertyCfgSheet.ItemDicEntry)


_ARCHITECTUREPROPERTYCFGSHEET_ITEMDICENTRY._options = None
# @@protoc_insertion_point(module_scope)
