# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: boss.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='boss.proto',
  package='DataConfig',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nboss.proto\x12\nDataConfig\"\xee\x05\n\x07\x42ossCfg\x12\x13\n\x06\x63\x66g_id\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x16\n\tboss_name\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x14\n\x07skin_id\x18\x03 \x01(\rH\x02\x88\x01\x01\x12\x15\n\x08skill_id\x18\x04 \x01(\rH\x03\x88\x01\x01\x12\x15\n\rskill_id_list\x18\x05 \x03(\r\x12\x1c\n\x0fmove_controller\x18\x06 \x01(\tH\x04\x88\x01\x01\x12\x16\n\thead_icon\x18\x07 \x01(\tH\x05\x88\x01\x01\x12\x14\n\x07\x64rop_id\x18\x08 \x01(\rH\x06\x88\x01\x01\x12\x12\n\x05motto\x18\t \x01(\tH\x07\x88\x01\x01\x12\x12\n\x05story\x18\n \x01(\tH\x08\x88\x01\x01\x12\x15\n\x08priority\x18\x0b \x01(\rH\t\x88\x01\x01\x12\x11\n\x04\x63\x61mp\x18\x0c \x01(\rH\n\x88\x01\x01\x12\x15\n\x08hp_value\x18\r \x01(\x02H\x0b\x88\x01\x01\x12=\n\tinfo_list\x18\x0e \x03(\x0b\x32*.DataConfig.BossCfg.InternalType_info_list\x12\x14\n\x07\x64isable\x18\x0f \x01(\x08H\x0c\x88\x01\x01\x12=\n\tattr_list\x18\x10 \x03(\x0b\x32*.DataConfig.BossCfg.InternalType_attr_list\x1aP\n\x16InternalType_info_list\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04info\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x07\n\x05_nameB\x07\n\x05_info\x1a\x34\n\x16InternalType_attr_list\x12\x11\n\x04\x61ttr\x18\x01 \x01(\x02H\x00\x88\x01\x01\x42\x07\n\x05_attrB\t\n\x07_cfg_idB\x0c\n\n_boss_nameB\n\n\x08_skin_idB\x0b\n\t_skill_idB\x12\n\x10_move_controllerB\x0c\n\n_head_iconB\n\n\x08_drop_idB\x08\n\x06_mottoB\x08\n\x06_storyB\x0b\n\t_priorityB\x07\n\x05_campB\x0b\n\t_hp_valueB\n\n\x08_disable\"\x8c\x01\n\x0c\x42ossCfgSheet\x12\x37\n\x08item_dic\x18\x01 \x03(\x0b\x32%.DataConfig.BossCfgSheet.ItemDicEntry\x1a\x43\n\x0cItemDicEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.DataConfig.BossCfg:\x02\x38\x01\x62\x06proto3'
)




_BOSSCFG_INTERNALTYPE_INFO_LIST = _descriptor.Descriptor(
  name='InternalType_info_list',
  full_name='DataConfig.BossCfg.InternalType_info_list',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='DataConfig.BossCfg.InternalType_info_list.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='info', full_name='DataConfig.BossCfg.InternalType_info_list.info', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_name', full_name='DataConfig.BossCfg.InternalType_info_list._name',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_info', full_name='DataConfig.BossCfg.InternalType_info_list._info',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=480,
  serialized_end=560,
)

_BOSSCFG_INTERNALTYPE_ATTR_LIST = _descriptor.Descriptor(
  name='InternalType_attr_list',
  full_name='DataConfig.BossCfg.InternalType_attr_list',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='attr', full_name='DataConfig.BossCfg.InternalType_attr_list.attr', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_attr', full_name='DataConfig.BossCfg.InternalType_attr_list._attr',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=562,
  serialized_end=614,
)

_BOSSCFG = _descriptor.Descriptor(
  name='BossCfg',
  full_name='DataConfig.BossCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cfg_id', full_name='DataConfig.BossCfg.cfg_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='boss_name', full_name='DataConfig.BossCfg.boss_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='skin_id', full_name='DataConfig.BossCfg.skin_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='skill_id', full_name='DataConfig.BossCfg.skill_id', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='skill_id_list', full_name='DataConfig.BossCfg.skill_id_list', index=4,
      number=5, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='move_controller', full_name='DataConfig.BossCfg.move_controller', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='head_icon', full_name='DataConfig.BossCfg.head_icon', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='drop_id', full_name='DataConfig.BossCfg.drop_id', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='motto', full_name='DataConfig.BossCfg.motto', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='story', full_name='DataConfig.BossCfg.story', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='priority', full_name='DataConfig.BossCfg.priority', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='camp', full_name='DataConfig.BossCfg.camp', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hp_value', full_name='DataConfig.BossCfg.hp_value', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='info_list', full_name='DataConfig.BossCfg.info_list', index=13,
      number=14, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='disable', full_name='DataConfig.BossCfg.disable', index=14,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attr_list', full_name='DataConfig.BossCfg.attr_list', index=15,
      number=16, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_BOSSCFG_INTERNALTYPE_INFO_LIST, _BOSSCFG_INTERNALTYPE_ATTR_LIST, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_cfg_id', full_name='DataConfig.BossCfg._cfg_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_boss_name', full_name='DataConfig.BossCfg._boss_name',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_skin_id', full_name='DataConfig.BossCfg._skin_id',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_skill_id', full_name='DataConfig.BossCfg._skill_id',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_move_controller', full_name='DataConfig.BossCfg._move_controller',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_head_icon', full_name='DataConfig.BossCfg._head_icon',
      index=5, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_drop_id', full_name='DataConfig.BossCfg._drop_id',
      index=6, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_motto', full_name='DataConfig.BossCfg._motto',
      index=7, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_story', full_name='DataConfig.BossCfg._story',
      index=8, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_priority', full_name='DataConfig.BossCfg._priority',
      index=9, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_camp', full_name='DataConfig.BossCfg._camp',
      index=10, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_hp_value', full_name='DataConfig.BossCfg._hp_value',
      index=11, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_disable', full_name='DataConfig.BossCfg._disable',
      index=12, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=27,
  serialized_end=777,
)


_BOSSCFGSHEET_ITEMDICENTRY = _descriptor.Descriptor(
  name='ItemDicEntry',
  full_name='DataConfig.BossCfgSheet.ItemDicEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DataConfig.BossCfgSheet.ItemDicEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='DataConfig.BossCfgSheet.ItemDicEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=853,
  serialized_end=920,
)

_BOSSCFGSHEET = _descriptor.Descriptor(
  name='BossCfgSheet',
  full_name='DataConfig.BossCfgSheet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_dic', full_name='DataConfig.BossCfgSheet.item_dic', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_BOSSCFGSHEET_ITEMDICENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=780,
  serialized_end=920,
)

_BOSSCFG_INTERNALTYPE_INFO_LIST.containing_type = _BOSSCFG
_BOSSCFG_INTERNALTYPE_INFO_LIST.oneofs_by_name['_name'].fields.append(
  _BOSSCFG_INTERNALTYPE_INFO_LIST.fields_by_name['name'])
_BOSSCFG_INTERNALTYPE_INFO_LIST.fields_by_name['name'].containing_oneof = _BOSSCFG_INTERNALTYPE_INFO_LIST.oneofs_by_name['_name']
_BOSSCFG_INTERNALTYPE_INFO_LIST.oneofs_by_name['_info'].fields.append(
  _BOSSCFG_INTERNALTYPE_INFO_LIST.fields_by_name['info'])
_BOSSCFG_INTERNALTYPE_INFO_LIST.fields_by_name['info'].containing_oneof = _BOSSCFG_INTERNALTYPE_INFO_LIST.oneofs_by_name['_info']
_BOSSCFG_INTERNALTYPE_ATTR_LIST.containing_type = _BOSSCFG
_BOSSCFG_INTERNALTYPE_ATTR_LIST.oneofs_by_name['_attr'].fields.append(
  _BOSSCFG_INTERNALTYPE_ATTR_LIST.fields_by_name['attr'])
_BOSSCFG_INTERNALTYPE_ATTR_LIST.fields_by_name['attr'].containing_oneof = _BOSSCFG_INTERNALTYPE_ATTR_LIST.oneofs_by_name['_attr']
_BOSSCFG.fields_by_name['info_list'].message_type = _BOSSCFG_INTERNALTYPE_INFO_LIST
_BOSSCFG.fields_by_name['attr_list'].message_type = _BOSSCFG_INTERNALTYPE_ATTR_LIST
_BOSSCFG.oneofs_by_name['_cfg_id'].fields.append(
  _BOSSCFG.fields_by_name['cfg_id'])
_BOSSCFG.fields_by_name['cfg_id'].containing_oneof = _BOSSCFG.oneofs_by_name['_cfg_id']
_BOSSCFG.oneofs_by_name['_boss_name'].fields.append(
  _BOSSCFG.fields_by_name['boss_name'])
_BOSSCFG.fields_by_name['boss_name'].containing_oneof = _BOSSCFG.oneofs_by_name['_boss_name']
_BOSSCFG.oneofs_by_name['_skin_id'].fields.append(
  _BOSSCFG.fields_by_name['skin_id'])
_BOSSCFG.fields_by_name['skin_id'].containing_oneof = _BOSSCFG.oneofs_by_name['_skin_id']
_BOSSCFG.oneofs_by_name['_skill_id'].fields.append(
  _BOSSCFG.fields_by_name['skill_id'])
_BOSSCFG.fields_by_name['skill_id'].containing_oneof = _BOSSCFG.oneofs_by_name['_skill_id']
_BOSSCFG.oneofs_by_name['_move_controller'].fields.append(
  _BOSSCFG.fields_by_name['move_controller'])
_BOSSCFG.fields_by_name['move_controller'].containing_oneof = _BOSSCFG.oneofs_by_name['_move_controller']
_BOSSCFG.oneofs_by_name['_head_icon'].fields.append(
  _BOSSCFG.fields_by_name['head_icon'])
_BOSSCFG.fields_by_name['head_icon'].containing_oneof = _BOSSCFG.oneofs_by_name['_head_icon']
_BOSSCFG.oneofs_by_name['_drop_id'].fields.append(
  _BOSSCFG.fields_by_name['drop_id'])
_BOSSCFG.fields_by_name['drop_id'].containing_oneof = _BOSSCFG.oneofs_by_name['_drop_id']
_BOSSCFG.oneofs_by_name['_motto'].fields.append(
  _BOSSCFG.fields_by_name['motto'])
_BOSSCFG.fields_by_name['motto'].containing_oneof = _BOSSCFG.oneofs_by_name['_motto']
_BOSSCFG.oneofs_by_name['_story'].fields.append(
  _BOSSCFG.fields_by_name['story'])
_BOSSCFG.fields_by_name['story'].containing_oneof = _BOSSCFG.oneofs_by_name['_story']
_BOSSCFG.oneofs_by_name['_priority'].fields.append(
  _BOSSCFG.fields_by_name['priority'])
_BOSSCFG.fields_by_name['priority'].containing_oneof = _BOSSCFG.oneofs_by_name['_priority']
_BOSSCFG.oneofs_by_name['_camp'].fields.append(
  _BOSSCFG.fields_by_name['camp'])
_BOSSCFG.fields_by_name['camp'].containing_oneof = _BOSSCFG.oneofs_by_name['_camp']
_BOSSCFG.oneofs_by_name['_hp_value'].fields.append(
  _BOSSCFG.fields_by_name['hp_value'])
_BOSSCFG.fields_by_name['hp_value'].containing_oneof = _BOSSCFG.oneofs_by_name['_hp_value']
_BOSSCFG.oneofs_by_name['_disable'].fields.append(
  _BOSSCFG.fields_by_name['disable'])
_BOSSCFG.fields_by_name['disable'].containing_oneof = _BOSSCFG.oneofs_by_name['_disable']
_BOSSCFGSHEET_ITEMDICENTRY.fields_by_name['value'].message_type = _BOSSCFG
_BOSSCFGSHEET_ITEMDICENTRY.containing_type = _BOSSCFGSHEET
_BOSSCFGSHEET.fields_by_name['item_dic'].message_type = _BOSSCFGSHEET_ITEMDICENTRY
DESCRIPTOR.message_types_by_name['BossCfg'] = _BOSSCFG
DESCRIPTOR.message_types_by_name['BossCfgSheet'] = _BOSSCFGSHEET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BossCfg = _reflection.GeneratedProtocolMessageType('BossCfg', (_message.Message,), {

  'InternalType_info_list' : _reflection.GeneratedProtocolMessageType('InternalType_info_list', (_message.Message,), {
    'DESCRIPTOR' : _BOSSCFG_INTERNALTYPE_INFO_LIST,
    '__module__' : 'boss_pb2'
    # @@protoc_insertion_point(class_scope:DataConfig.BossCfg.InternalType_info_list)
    })
  ,

  'InternalType_attr_list' : _reflection.GeneratedProtocolMessageType('InternalType_attr_list', (_message.Message,), {
    'DESCRIPTOR' : _BOSSCFG_INTERNALTYPE_ATTR_LIST,
    '__module__' : 'boss_pb2'
    # @@protoc_insertion_point(class_scope:DataConfig.BossCfg.InternalType_attr_list)
    })
  ,
  'DESCRIPTOR' : _BOSSCFG,
  '__module__' : 'boss_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.BossCfg)
  })
_sym_db.RegisterMessage(BossCfg)
_sym_db.RegisterMessage(BossCfg.InternalType_info_list)
_sym_db.RegisterMessage(BossCfg.InternalType_attr_list)

BossCfgSheet = _reflection.GeneratedProtocolMessageType('BossCfgSheet', (_message.Message,), {

  'ItemDicEntry' : _reflection.GeneratedProtocolMessageType('ItemDicEntry', (_message.Message,), {
    'DESCRIPTOR' : _BOSSCFGSHEET_ITEMDICENTRY,
    '__module__' : 'boss_pb2'
    # @@protoc_insertion_point(class_scope:DataConfig.BossCfgSheet.ItemDicEntry)
    })
  ,
  'DESCRIPTOR' : _BOSSCFGSHEET,
  '__module__' : 'boss_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.BossCfgSheet)
  })
_sym_db.RegisterMessage(BossCfgSheet)
_sym_db.RegisterMessage(BossCfgSheet.ItemDicEntry)


_BOSSCFGSHEET_ITEMDICENTRY._options = None
# @@protoc_insertion_point(module_scope)
