# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: box.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='box.proto',
  package='DataConfig',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tbox.proto\x12\nDataConfig\"\xe0\x01\n\x06\x42oxCfg\x12\x13\n\x06\x63\x66g_id\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x11\n\x04name\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x14\n\x07prop_id\x18\x03 \x01(\rH\x02\x88\x01\x01\x12\x15\n\x08model_id\x18\x04 \x01(\rH\x03\x88\x01\x01\x12\x13\n\x06\x64uring\x18\x05 \x01(\x02H\x04\x88\x01\x01\x12\x1e\n\x11probability_index\x18\x06 \x01(\rH\x05\x88\x01\x01\x42\t\n\x07_cfg_idB\x07\n\x05_nameB\n\n\x08_prop_idB\x0b\n\t_model_idB\t\n\x07_duringB\x14\n\x12_probability_index\"\x89\x01\n\x0b\x42oxCfgSheet\x12\x36\n\x08item_dic\x18\x01 \x03(\x0b\x32$.DataConfig.BoxCfgSheet.ItemDicEntry\x1a\x42\n\x0cItemDicEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.DataConfig.BoxCfg:\x02\x38\x01\x62\x06proto3'
)




_BOXCFG = _descriptor.Descriptor(
  name='BoxCfg',
  full_name='DataConfig.BoxCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cfg_id', full_name='DataConfig.BoxCfg.cfg_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='DataConfig.BoxCfg.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prop_id', full_name='DataConfig.BoxCfg.prop_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_id', full_name='DataConfig.BoxCfg.model_id', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='during', full_name='DataConfig.BoxCfg.during', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='probability_index', full_name='DataConfig.BoxCfg.probability_index', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_cfg_id', full_name='DataConfig.BoxCfg._cfg_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_name', full_name='DataConfig.BoxCfg._name',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_prop_id', full_name='DataConfig.BoxCfg._prop_id',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_model_id', full_name='DataConfig.BoxCfg._model_id',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_during', full_name='DataConfig.BoxCfg._during',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_probability_index', full_name='DataConfig.BoxCfg._probability_index',
      index=5, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=26,
  serialized_end=250,
)


_BOXCFGSHEET_ITEMDICENTRY = _descriptor.Descriptor(
  name='ItemDicEntry',
  full_name='DataConfig.BoxCfgSheet.ItemDicEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DataConfig.BoxCfgSheet.ItemDicEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='DataConfig.BoxCfgSheet.ItemDicEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=324,
  serialized_end=390,
)

_BOXCFGSHEET = _descriptor.Descriptor(
  name='BoxCfgSheet',
  full_name='DataConfig.BoxCfgSheet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_dic', full_name='DataConfig.BoxCfgSheet.item_dic', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_BOXCFGSHEET_ITEMDICENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=390,
)

_BOXCFG.oneofs_by_name['_cfg_id'].fields.append(
  _BOXCFG.fields_by_name['cfg_id'])
_BOXCFG.fields_by_name['cfg_id'].containing_oneof = _BOXCFG.oneofs_by_name['_cfg_id']
_BOXCFG.oneofs_by_name['_name'].fields.append(
  _BOXCFG.fields_by_name['name'])
_BOXCFG.fields_by_name['name'].containing_oneof = _BOXCFG.oneofs_by_name['_name']
_BOXCFG.oneofs_by_name['_prop_id'].fields.append(
  _BOXCFG.fields_by_name['prop_id'])
_BOXCFG.fields_by_name['prop_id'].containing_oneof = _BOXCFG.oneofs_by_name['_prop_id']
_BOXCFG.oneofs_by_name['_model_id'].fields.append(
  _BOXCFG.fields_by_name['model_id'])
_BOXCFG.fields_by_name['model_id'].containing_oneof = _BOXCFG.oneofs_by_name['_model_id']
_BOXCFG.oneofs_by_name['_during'].fields.append(
  _BOXCFG.fields_by_name['during'])
_BOXCFG.fields_by_name['during'].containing_oneof = _BOXCFG.oneofs_by_name['_during']
_BOXCFG.oneofs_by_name['_probability_index'].fields.append(
  _BOXCFG.fields_by_name['probability_index'])
_BOXCFG.fields_by_name['probability_index'].containing_oneof = _BOXCFG.oneofs_by_name['_probability_index']
_BOXCFGSHEET_ITEMDICENTRY.fields_by_name['value'].message_type = _BOXCFG
_BOXCFGSHEET_ITEMDICENTRY.containing_type = _BOXCFGSHEET
_BOXCFGSHEET.fields_by_name['item_dic'].message_type = _BOXCFGSHEET_ITEMDICENTRY
DESCRIPTOR.message_types_by_name['BoxCfg'] = _BOXCFG
DESCRIPTOR.message_types_by_name['BoxCfgSheet'] = _BOXCFGSHEET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BoxCfg = _reflection.GeneratedProtocolMessageType('BoxCfg', (_message.Message,), {
  'DESCRIPTOR' : _BOXCFG,
  '__module__' : 'box_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.BoxCfg)
  })
_sym_db.RegisterMessage(BoxCfg)

BoxCfgSheet = _reflection.GeneratedProtocolMessageType('BoxCfgSheet', (_message.Message,), {

  'ItemDicEntry' : _reflection.GeneratedProtocolMessageType('ItemDicEntry', (_message.Message,), {
    'DESCRIPTOR' : _BOXCFGSHEET_ITEMDICENTRY,
    '__module__' : 'box_pb2'
    # @@protoc_insertion_point(class_scope:DataConfig.BoxCfgSheet.ItemDicEntry)
    })
  ,
  'DESCRIPTOR' : _BOXCFGSHEET,
  '__module__' : 'box_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.BoxCfgSheet)
  })
_sym_db.RegisterMessage(BoxCfgSheet)
_sym_db.RegisterMessage(BoxCfgSheet.ItemDicEntry)


_BOXCFGSHEET_ITEMDICENTRY._options = None
# @@protoc_insertion_point(module_scope)
