# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buff.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='buff.proto',
  package='DataConfig',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nbuff.proto\x12\nDataConfig\"\xf3\x05\n\x07\x42uffCfg\x12\x13\n\x06\x63\x66g_id\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x15\n\x08group_id\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x11\n\x04name\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x13\n\x0b\x65ntity_type\x18\x04 \x03(\r\x12\x1a\n\rsuperposition\x18\x05 \x01(\rH\x03\x88\x01\x01\x12\x17\n\nreset_type\x18\x06 \x01(\rH\x04\x88\x01\x01\x12\x16\n\tdispersed\x18\x07 \x01(\x08H\x05\x88\x01\x01\x12\x16\n\tclass_tag\x18\x08 \x01(\rH\x06\x88\x01\x01\x12\x16\n\tother_tag\x18\t \x01(\tH\x07\x88\x01\x01\x12\x15\n\x08is_delay\x18\n \x01(\x08H\x08\x88\x01\x01\x12\x16\n\thidden_cd\x18\x0b \x01(\x08H\t\x88\x01\x01\x12\x1a\n\rmaterial_path\x18\x0c \x01(\tH\n\x88\x01\x01\x12\x18\n\x0b\x65\x66\x66\x65\x63t_path\x18\r \x01(\tH\x0b\x88\x01\x01\x12\x15\n\rclient_effect\x18\x0e \x03(\r\x12\x1c\n\x0f\x65\x66\x66\x65\x63tive_event\x18\x0f \x01(\tH\x0c\x88\x01\x01\x12\x1f\n\x12\x65\x66\x66\x65\x63t_probability\x18\x10 \x01(\x02H\r\x88\x01\x01\x12\x18\n\x0b\x62uff_effect\x18\x11 \x01(\tH\x0e\x88\x01\x01\x12\x1d\n\x10remove_condition\x18\x12 \x01(\tH\x0f\x88\x01\x01\x12\x19\n\x0cremove_count\x18\x13 \x01(\rH\x10\x88\x01\x01\x42\t\n\x07_cfg_idB\x0b\n\t_group_idB\x07\n\x05_nameB\x10\n\x0e_superpositionB\r\n\x0b_reset_typeB\x0c\n\n_dispersedB\x0c\n\n_class_tagB\x0c\n\n_other_tagB\x0b\n\t_is_delayB\x0c\n\n_hidden_cdB\x10\n\x0e_material_pathB\x0e\n\x0c_effect_pathB\x12\n\x10_effective_eventB\x15\n\x13_effect_probabilityB\x0e\n\x0c_buff_effectB\x13\n\x11_remove_conditionB\x0f\n\r_remove_count\"\x8c\x01\n\x0c\x42uffCfgSheet\x12\x37\n\x08item_dic\x18\x01 \x03(\x0b\x32%.DataConfig.BuffCfgSheet.ItemDicEntry\x1a\x43\n\x0cItemDicEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.DataConfig.BuffCfg:\x02\x38\x01\x62\x06proto3'
)




_BUFFCFG = _descriptor.Descriptor(
  name='BuffCfg',
  full_name='DataConfig.BuffCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cfg_id', full_name='DataConfig.BuffCfg.cfg_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='group_id', full_name='DataConfig.BuffCfg.group_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='DataConfig.BuffCfg.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entity_type', full_name='DataConfig.BuffCfg.entity_type', index=3,
      number=4, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='superposition', full_name='DataConfig.BuffCfg.superposition', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reset_type', full_name='DataConfig.BuffCfg.reset_type', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dispersed', full_name='DataConfig.BuffCfg.dispersed', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='class_tag', full_name='DataConfig.BuffCfg.class_tag', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='other_tag', full_name='DataConfig.BuffCfg.other_tag', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_delay', full_name='DataConfig.BuffCfg.is_delay', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hidden_cd', full_name='DataConfig.BuffCfg.hidden_cd', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='material_path', full_name='DataConfig.BuffCfg.material_path', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='effect_path', full_name='DataConfig.BuffCfg.effect_path', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_effect', full_name='DataConfig.BuffCfg.client_effect', index=13,
      number=14, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='effective_event', full_name='DataConfig.BuffCfg.effective_event', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='effect_probability', full_name='DataConfig.BuffCfg.effect_probability', index=15,
      number=16, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='buff_effect', full_name='DataConfig.BuffCfg.buff_effect', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='remove_condition', full_name='DataConfig.BuffCfg.remove_condition', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='remove_count', full_name='DataConfig.BuffCfg.remove_count', index=18,
      number=19, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_cfg_id', full_name='DataConfig.BuffCfg._cfg_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_group_id', full_name='DataConfig.BuffCfg._group_id',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_name', full_name='DataConfig.BuffCfg._name',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_superposition', full_name='DataConfig.BuffCfg._superposition',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_reset_type', full_name='DataConfig.BuffCfg._reset_type',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_dispersed', full_name='DataConfig.BuffCfg._dispersed',
      index=5, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_class_tag', full_name='DataConfig.BuffCfg._class_tag',
      index=6, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_other_tag', full_name='DataConfig.BuffCfg._other_tag',
      index=7, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_is_delay', full_name='DataConfig.BuffCfg._is_delay',
      index=8, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_hidden_cd', full_name='DataConfig.BuffCfg._hidden_cd',
      index=9, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_material_path', full_name='DataConfig.BuffCfg._material_path',
      index=10, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_effect_path', full_name='DataConfig.BuffCfg._effect_path',
      index=11, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_effective_event', full_name='DataConfig.BuffCfg._effective_event',
      index=12, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_effect_probability', full_name='DataConfig.BuffCfg._effect_probability',
      index=13, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_buff_effect', full_name='DataConfig.BuffCfg._buff_effect',
      index=14, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_remove_condition', full_name='DataConfig.BuffCfg._remove_condition',
      index=15, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_remove_count', full_name='DataConfig.BuffCfg._remove_count',
      index=16, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=27,
  serialized_end=782,
)


_BUFFCFGSHEET_ITEMDICENTRY = _descriptor.Descriptor(
  name='ItemDicEntry',
  full_name='DataConfig.BuffCfgSheet.ItemDicEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DataConfig.BuffCfgSheet.ItemDicEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='DataConfig.BuffCfgSheet.ItemDicEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=858,
  serialized_end=925,
)

_BUFFCFGSHEET = _descriptor.Descriptor(
  name='BuffCfgSheet',
  full_name='DataConfig.BuffCfgSheet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_dic', full_name='DataConfig.BuffCfgSheet.item_dic', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_BUFFCFGSHEET_ITEMDICENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=785,
  serialized_end=925,
)

_BUFFCFG.oneofs_by_name['_cfg_id'].fields.append(
  _BUFFCFG.fields_by_name['cfg_id'])
_BUFFCFG.fields_by_name['cfg_id'].containing_oneof = _BUFFCFG.oneofs_by_name['_cfg_id']
_BUFFCFG.oneofs_by_name['_group_id'].fields.append(
  _BUFFCFG.fields_by_name['group_id'])
_BUFFCFG.fields_by_name['group_id'].containing_oneof = _BUFFCFG.oneofs_by_name['_group_id']
_BUFFCFG.oneofs_by_name['_name'].fields.append(
  _BUFFCFG.fields_by_name['name'])
_BUFFCFG.fields_by_name['name'].containing_oneof = _BUFFCFG.oneofs_by_name['_name']
_BUFFCFG.oneofs_by_name['_superposition'].fields.append(
  _BUFFCFG.fields_by_name['superposition'])
_BUFFCFG.fields_by_name['superposition'].containing_oneof = _BUFFCFG.oneofs_by_name['_superposition']
_BUFFCFG.oneofs_by_name['_reset_type'].fields.append(
  _BUFFCFG.fields_by_name['reset_type'])
_BUFFCFG.fields_by_name['reset_type'].containing_oneof = _BUFFCFG.oneofs_by_name['_reset_type']
_BUFFCFG.oneofs_by_name['_dispersed'].fields.append(
  _BUFFCFG.fields_by_name['dispersed'])
_BUFFCFG.fields_by_name['dispersed'].containing_oneof = _BUFFCFG.oneofs_by_name['_dispersed']
_BUFFCFG.oneofs_by_name['_class_tag'].fields.append(
  _BUFFCFG.fields_by_name['class_tag'])
_BUFFCFG.fields_by_name['class_tag'].containing_oneof = _BUFFCFG.oneofs_by_name['_class_tag']
_BUFFCFG.oneofs_by_name['_other_tag'].fields.append(
  _BUFFCFG.fields_by_name['other_tag'])
_BUFFCFG.fields_by_name['other_tag'].containing_oneof = _BUFFCFG.oneofs_by_name['_other_tag']
_BUFFCFG.oneofs_by_name['_is_delay'].fields.append(
  _BUFFCFG.fields_by_name['is_delay'])
_BUFFCFG.fields_by_name['is_delay'].containing_oneof = _BUFFCFG.oneofs_by_name['_is_delay']
_BUFFCFG.oneofs_by_name['_hidden_cd'].fields.append(
  _BUFFCFG.fields_by_name['hidden_cd'])
_BUFFCFG.fields_by_name['hidden_cd'].containing_oneof = _BUFFCFG.oneofs_by_name['_hidden_cd']
_BUFFCFG.oneofs_by_name['_material_path'].fields.append(
  _BUFFCFG.fields_by_name['material_path'])
_BUFFCFG.fields_by_name['material_path'].containing_oneof = _BUFFCFG.oneofs_by_name['_material_path']
_BUFFCFG.oneofs_by_name['_effect_path'].fields.append(
  _BUFFCFG.fields_by_name['effect_path'])
_BUFFCFG.fields_by_name['effect_path'].containing_oneof = _BUFFCFG.oneofs_by_name['_effect_path']
_BUFFCFG.oneofs_by_name['_effective_event'].fields.append(
  _BUFFCFG.fields_by_name['effective_event'])
_BUFFCFG.fields_by_name['effective_event'].containing_oneof = _BUFFCFG.oneofs_by_name['_effective_event']
_BUFFCFG.oneofs_by_name['_effect_probability'].fields.append(
  _BUFFCFG.fields_by_name['effect_probability'])
_BUFFCFG.fields_by_name['effect_probability'].containing_oneof = _BUFFCFG.oneofs_by_name['_effect_probability']
_BUFFCFG.oneofs_by_name['_buff_effect'].fields.append(
  _BUFFCFG.fields_by_name['buff_effect'])
_BUFFCFG.fields_by_name['buff_effect'].containing_oneof = _BUFFCFG.oneofs_by_name['_buff_effect']
_BUFFCFG.oneofs_by_name['_remove_condition'].fields.append(
  _BUFFCFG.fields_by_name['remove_condition'])
_BUFFCFG.fields_by_name['remove_condition'].containing_oneof = _BUFFCFG.oneofs_by_name['_remove_condition']
_BUFFCFG.oneofs_by_name['_remove_count'].fields.append(
  _BUFFCFG.fields_by_name['remove_count'])
_BUFFCFG.fields_by_name['remove_count'].containing_oneof = _BUFFCFG.oneofs_by_name['_remove_count']
_BUFFCFGSHEET_ITEMDICENTRY.fields_by_name['value'].message_type = _BUFFCFG
_BUFFCFGSHEET_ITEMDICENTRY.containing_type = _BUFFCFGSHEET
_BUFFCFGSHEET.fields_by_name['item_dic'].message_type = _BUFFCFGSHEET_ITEMDICENTRY
DESCRIPTOR.message_types_by_name['BuffCfg'] = _BUFFCFG
DESCRIPTOR.message_types_by_name['BuffCfgSheet'] = _BUFFCFGSHEET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BuffCfg = _reflection.GeneratedProtocolMessageType('BuffCfg', (_message.Message,), {
  'DESCRIPTOR' : _BUFFCFG,
  '__module__' : 'buff_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.BuffCfg)
  })
_sym_db.RegisterMessage(BuffCfg)

BuffCfgSheet = _reflection.GeneratedProtocolMessageType('BuffCfgSheet', (_message.Message,), {

  'ItemDicEntry' : _reflection.GeneratedProtocolMessageType('ItemDicEntry', (_message.Message,), {
    'DESCRIPTOR' : _BUFFCFGSHEET_ITEMDICENTRY,
    '__module__' : 'buff_pb2'
    # @@protoc_insertion_point(class_scope:DataConfig.BuffCfgSheet.ItemDicEntry)
    })
  ,
  'DESCRIPTOR' : _BUFFCFGSHEET,
  '__module__' : 'buff_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.BuffCfgSheet)
  })
_sym_db.RegisterMessage(BuffCfgSheet)
_sym_db.RegisterMessage(BuffCfgSheet.ItemDicEntry)


_BUFFCFGSHEET_ITEMDICENTRY._options = None
# @@protoc_insertion_point(module_scope)
