# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buffclienteffect.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='buffclienteffect.proto',
  package='DataConfig',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x62uffclienteffect.proto\x12\nDataConfig\"m\n\x13\x42uffClientEffectCfg\x12\x13\n\x06\x63\x66g_id\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x11\n\x04type\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x11\n\x04json\x18\x03 \x01(\tH\x02\x88\x01\x01\x42\t\n\x07_cfg_idB\x07\n\x05_typeB\x07\n\x05_json\"\xb0\x01\n\x18\x42uffClientEffectCfgSheet\x12\x43\n\x08item_dic\x18\x01 \x03(\x0b\x32\x31.DataConfig.BuffClientEffectCfgSheet.ItemDicEntry\x1aO\n\x0cItemDicEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12.\n\x05value\x18\x02 \x01(\x0b\x32\x1f.DataConfig.BuffClientEffectCfg:\x02\x38\x01\x62\x06proto3'
)




_BUFFCLIENTEFFECTCFG = _descriptor.Descriptor(
  name='BuffClientEffectCfg',
  full_name='DataConfig.BuffClientEffectCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cfg_id', full_name='DataConfig.BuffClientEffectCfg.cfg_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='DataConfig.BuffClientEffectCfg.type', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='json', full_name='DataConfig.BuffClientEffectCfg.json', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_cfg_id', full_name='DataConfig.BuffClientEffectCfg._cfg_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_type', full_name='DataConfig.BuffClientEffectCfg._type',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_json', full_name='DataConfig.BuffClientEffectCfg._json',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=38,
  serialized_end=147,
)


_BUFFCLIENTEFFECTCFGSHEET_ITEMDICENTRY = _descriptor.Descriptor(
  name='ItemDicEntry',
  full_name='DataConfig.BuffClientEffectCfgSheet.ItemDicEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DataConfig.BuffClientEffectCfgSheet.ItemDicEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='DataConfig.BuffClientEffectCfgSheet.ItemDicEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=326,
)

_BUFFCLIENTEFFECTCFGSHEET = _descriptor.Descriptor(
  name='BuffClientEffectCfgSheet',
  full_name='DataConfig.BuffClientEffectCfgSheet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_dic', full_name='DataConfig.BuffClientEffectCfgSheet.item_dic', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_BUFFCLIENTEFFECTCFGSHEET_ITEMDICENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=326,
)

_BUFFCLIENTEFFECTCFG.oneofs_by_name['_cfg_id'].fields.append(
  _BUFFCLIENTEFFECTCFG.fields_by_name['cfg_id'])
_BUFFCLIENTEFFECTCFG.fields_by_name['cfg_id'].containing_oneof = _BUFFCLIENTEFFECTCFG.oneofs_by_name['_cfg_id']
_BUFFCLIENTEFFECTCFG.oneofs_by_name['_type'].fields.append(
  _BUFFCLIENTEFFECTCFG.fields_by_name['type'])
_BUFFCLIENTEFFECTCFG.fields_by_name['type'].containing_oneof = _BUFFCLIENTEFFECTCFG.oneofs_by_name['_type']
_BUFFCLIENTEFFECTCFG.oneofs_by_name['_json'].fields.append(
  _BUFFCLIENTEFFECTCFG.fields_by_name['json'])
_BUFFCLIENTEFFECTCFG.fields_by_name['json'].containing_oneof = _BUFFCLIENTEFFECTCFG.oneofs_by_name['_json']
_BUFFCLIENTEFFECTCFGSHEET_ITEMDICENTRY.fields_by_name['value'].message_type = _BUFFCLIENTEFFECTCFG
_BUFFCLIENTEFFECTCFGSHEET_ITEMDICENTRY.containing_type = _BUFFCLIENTEFFECTCFGSHEET
_BUFFCLIENTEFFECTCFGSHEET.fields_by_name['item_dic'].message_type = _BUFFCLIENTEFFECTCFGSHEET_ITEMDICENTRY
DESCRIPTOR.message_types_by_name['BuffClientEffectCfg'] = _BUFFCLIENTEFFECTCFG
DESCRIPTOR.message_types_by_name['BuffClientEffectCfgSheet'] = _BUFFCLIENTEFFECTCFGSHEET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BuffClientEffectCfg = _reflection.GeneratedProtocolMessageType('BuffClientEffectCfg', (_message.Message,), {
  'DESCRIPTOR' : _BUFFCLIENTEFFECTCFG,
  '__module__' : 'buffclienteffect_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.BuffClientEffectCfg)
  })
_sym_db.RegisterMessage(BuffClientEffectCfg)

BuffClientEffectCfgSheet = _reflection.GeneratedProtocolMessageType('BuffClientEffectCfgSheet', (_message.Message,), {

  'ItemDicEntry' : _reflection.GeneratedProtocolMessageType('ItemDicEntry', (_message.Message,), {
    'DESCRIPTOR' : _BUFFCLIENTEFFECTCFGSHEET_ITEMDICENTRY,
    '__module__' : 'buffclienteffect_pb2'
    # @@protoc_insertion_point(class_scope:DataConfig.BuffClientEffectCfgSheet.ItemDicEntry)
    })
  ,
  'DESCRIPTOR' : _BUFFCLIENTEFFECTCFGSHEET,
  '__module__' : 'buffclienteffect_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.BuffClientEffectCfgSheet)
  })
_sym_db.RegisterMessage(BuffClientEffectCfgSheet)
_sym_db.RegisterMessage(BuffClientEffectCfgSheet.ItemDicEntry)


_BUFFCLIENTEFFECTCFGSHEET_ITEMDICENTRY._options = None
# @@protoc_insertion_point(module_scope)
