# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buffeffect.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='buffeffect.proto',
  package='DataConfig',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x62uffeffect.proto\x12\nDataConfig\"\xbd\x01\n\rBuffeffectCfg\x12\x13\n\x06\x63\x66g_id\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x11\n\x04name\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x11\n\x04type\x18\x03 \x01(\rH\x02\x88\x01\x01\x12\x18\n\x0b\x66loat_param\x18\x04 \x01(\x02H\x03\x88\x01\x01\x12\x19\n\x0cstring_param\x18\x05 \x01(\tH\x04\x88\x01\x01\x42\t\n\x07_cfg_idB\x07\n\x05_nameB\x07\n\x05_typeB\x0e\n\x0c_float_paramB\x0f\n\r_string_param\"\x9e\x01\n\x12\x42uffeffectCfgSheet\x12=\n\x08item_dic\x18\x01 \x03(\x0b\x32+.DataConfig.BuffeffectCfgSheet.ItemDicEntry\x1aI\n\x0cItemDicEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.DataConfig.BuffeffectCfg:\x02\x38\x01\x62\x06proto3'
)




_BUFFEFFECTCFG = _descriptor.Descriptor(
  name='BuffeffectCfg',
  full_name='DataConfig.BuffeffectCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cfg_id', full_name='DataConfig.BuffeffectCfg.cfg_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='DataConfig.BuffeffectCfg.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='DataConfig.BuffeffectCfg.type', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='float_param', full_name='DataConfig.BuffeffectCfg.float_param', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='string_param', full_name='DataConfig.BuffeffectCfg.string_param', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_cfg_id', full_name='DataConfig.BuffeffectCfg._cfg_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_name', full_name='DataConfig.BuffeffectCfg._name',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_type', full_name='DataConfig.BuffeffectCfg._type',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_float_param', full_name='DataConfig.BuffeffectCfg._float_param',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_string_param', full_name='DataConfig.BuffeffectCfg._string_param',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=33,
  serialized_end=222,
)


_BUFFEFFECTCFGSHEET_ITEMDICENTRY = _descriptor.Descriptor(
  name='ItemDicEntry',
  full_name='DataConfig.BuffeffectCfgSheet.ItemDicEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DataConfig.BuffeffectCfgSheet.ItemDicEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='DataConfig.BuffeffectCfgSheet.ItemDicEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=310,
  serialized_end=383,
)

_BUFFEFFECTCFGSHEET = _descriptor.Descriptor(
  name='BuffeffectCfgSheet',
  full_name='DataConfig.BuffeffectCfgSheet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_dic', full_name='DataConfig.BuffeffectCfgSheet.item_dic', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_BUFFEFFECTCFGSHEET_ITEMDICENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=383,
)

_BUFFEFFECTCFG.oneofs_by_name['_cfg_id'].fields.append(
  _BUFFEFFECTCFG.fields_by_name['cfg_id'])
_BUFFEFFECTCFG.fields_by_name['cfg_id'].containing_oneof = _BUFFEFFECTCFG.oneofs_by_name['_cfg_id']
_BUFFEFFECTCFG.oneofs_by_name['_name'].fields.append(
  _BUFFEFFECTCFG.fields_by_name['name'])
_BUFFEFFECTCFG.fields_by_name['name'].containing_oneof = _BUFFEFFECTCFG.oneofs_by_name['_name']
_BUFFEFFECTCFG.oneofs_by_name['_type'].fields.append(
  _BUFFEFFECTCFG.fields_by_name['type'])
_BUFFEFFECTCFG.fields_by_name['type'].containing_oneof = _BUFFEFFECTCFG.oneofs_by_name['_type']
_BUFFEFFECTCFG.oneofs_by_name['_float_param'].fields.append(
  _BUFFEFFECTCFG.fields_by_name['float_param'])
_BUFFEFFECTCFG.fields_by_name['float_param'].containing_oneof = _BUFFEFFECTCFG.oneofs_by_name['_float_param']
_BUFFEFFECTCFG.oneofs_by_name['_string_param'].fields.append(
  _BUFFEFFECTCFG.fields_by_name['string_param'])
_BUFFEFFECTCFG.fields_by_name['string_param'].containing_oneof = _BUFFEFFECTCFG.oneofs_by_name['_string_param']
_BUFFEFFECTCFGSHEET_ITEMDICENTRY.fields_by_name['value'].message_type = _BUFFEFFECTCFG
_BUFFEFFECTCFGSHEET_ITEMDICENTRY.containing_type = _BUFFEFFECTCFGSHEET
_BUFFEFFECTCFGSHEET.fields_by_name['item_dic'].message_type = _BUFFEFFECTCFGSHEET_ITEMDICENTRY
DESCRIPTOR.message_types_by_name['BuffeffectCfg'] = _BUFFEFFECTCFG
DESCRIPTOR.message_types_by_name['BuffeffectCfgSheet'] = _BUFFEFFECTCFGSHEET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BuffeffectCfg = _reflection.GeneratedProtocolMessageType('BuffeffectCfg', (_message.Message,), {
  'DESCRIPTOR' : _BUFFEFFECTCFG,
  '__module__' : 'buffeffect_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.BuffeffectCfg)
  })
_sym_db.RegisterMessage(BuffeffectCfg)

BuffeffectCfgSheet = _reflection.GeneratedProtocolMessageType('BuffeffectCfgSheet', (_message.Message,), {

  'ItemDicEntry' : _reflection.GeneratedProtocolMessageType('ItemDicEntry', (_message.Message,), {
    'DESCRIPTOR' : _BUFFEFFECTCFGSHEET_ITEMDICENTRY,
    '__module__' : 'buffeffect_pb2'
    # @@protoc_insertion_point(class_scope:DataConfig.BuffeffectCfgSheet.ItemDicEntry)
    })
  ,
  'DESCRIPTOR' : _BUFFEFFECTCFGSHEET,
  '__module__' : 'buffeffect_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.BuffeffectCfgSheet)
  })
_sym_db.RegisterMessage(BuffeffectCfgSheet)
_sym_db.RegisterMessage(BuffeffectCfgSheet.ItemDicEntry)


_BUFFEFFECTCFGSHEET_ITEMDICENTRY._options = None
# @@protoc_insertion_point(module_scope)
