# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dropgroup.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dropgroup.proto',
  package='DataConfig',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x64ropgroup.proto\x12\nDataConfig\"\xaf\x03\n\x0c\x44ropGroupCfg\x12\x13\n\x06\x63\x66g_id\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x11\n\x04name\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x15\n\x08model_id\x18\x03 \x01(\rH\x02\x88\x01\x01\x12\x16\n\tpick_type\x18\x04 \x01(\rH\x03\x88\x01\x01\x12\x16\n\tdrop_type\x18\x05 \x01(\rH\x04\x88\x01\x01\x12J\n\rdrop_bag_list\x18\x06 \x03(\x0b\x32\x33.DataConfig.DropGroupCfg.InternalType_drop_bag_list\x1a\xa6\x01\n\x1aInternalType_drop_bag_list\x12\x18\n\x0b\x64rop_bag_id\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x19\n\x0c\x64rop_bag_num\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x1d\n\x10\x64rop_bag_percent\x18\x03 \x01(\x02H\x02\x88\x01\x01\x42\x0e\n\x0c_drop_bag_idB\x0f\n\r_drop_bag_numB\x13\n\x11_drop_bag_percentB\t\n\x07_cfg_idB\x07\n\x05_nameB\x0b\n\t_model_idB\x0c\n\n_pick_typeB\x0c\n\n_drop_type\"\x9b\x01\n\x11\x44ropGroupCfgSheet\x12<\n\x08item_dic\x18\x01 \x03(\x0b\x32*.DataConfig.DropGroupCfgSheet.ItemDicEntry\x1aH\n\x0cItemDicEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.DataConfig.DropGroupCfg:\x02\x38\x01\x62\x06proto3'
)




_DROPGROUPCFG_INTERNALTYPE_DROP_BAG_LIST = _descriptor.Descriptor(
  name='InternalType_drop_bag_list',
  full_name='DataConfig.DropGroupCfg.InternalType_drop_bag_list',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='drop_bag_id', full_name='DataConfig.DropGroupCfg.InternalType_drop_bag_list.drop_bag_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='drop_bag_num', full_name='DataConfig.DropGroupCfg.InternalType_drop_bag_list.drop_bag_num', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='drop_bag_percent', full_name='DataConfig.DropGroupCfg.InternalType_drop_bag_list.drop_bag_percent', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_drop_bag_id', full_name='DataConfig.DropGroupCfg.InternalType_drop_bag_list._drop_bag_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_drop_bag_num', full_name='DataConfig.DropGroupCfg.InternalType_drop_bag_list._drop_bag_num',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_drop_bag_percent', full_name='DataConfig.DropGroupCfg.InternalType_drop_bag_list._drop_bag_percent',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=236,
  serialized_end=402,
)

_DROPGROUPCFG = _descriptor.Descriptor(
  name='DropGroupCfg',
  full_name='DataConfig.DropGroupCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cfg_id', full_name='DataConfig.DropGroupCfg.cfg_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='DataConfig.DropGroupCfg.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_id', full_name='DataConfig.DropGroupCfg.model_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pick_type', full_name='DataConfig.DropGroupCfg.pick_type', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='drop_type', full_name='DataConfig.DropGroupCfg.drop_type', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='drop_bag_list', full_name='DataConfig.DropGroupCfg.drop_bag_list', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DROPGROUPCFG_INTERNALTYPE_DROP_BAG_LIST, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_cfg_id', full_name='DataConfig.DropGroupCfg._cfg_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_name', full_name='DataConfig.DropGroupCfg._name',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_model_id', full_name='DataConfig.DropGroupCfg._model_id',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_pick_type', full_name='DataConfig.DropGroupCfg._pick_type',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_drop_type', full_name='DataConfig.DropGroupCfg._drop_type',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=32,
  serialized_end=463,
)


_DROPGROUPCFGSHEET_ITEMDICENTRY = _descriptor.Descriptor(
  name='ItemDicEntry',
  full_name='DataConfig.DropGroupCfgSheet.ItemDicEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DataConfig.DropGroupCfgSheet.ItemDicEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='DataConfig.DropGroupCfgSheet.ItemDicEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=549,
  serialized_end=621,
)

_DROPGROUPCFGSHEET = _descriptor.Descriptor(
  name='DropGroupCfgSheet',
  full_name='DataConfig.DropGroupCfgSheet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_dic', full_name='DataConfig.DropGroupCfgSheet.item_dic', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DROPGROUPCFGSHEET_ITEMDICENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=466,
  serialized_end=621,
)

_DROPGROUPCFG_INTERNALTYPE_DROP_BAG_LIST.containing_type = _DROPGROUPCFG
_DROPGROUPCFG_INTERNALTYPE_DROP_BAG_LIST.oneofs_by_name['_drop_bag_id'].fields.append(
  _DROPGROUPCFG_INTERNALTYPE_DROP_BAG_LIST.fields_by_name['drop_bag_id'])
_DROPGROUPCFG_INTERNALTYPE_DROP_BAG_LIST.fields_by_name['drop_bag_id'].containing_oneof = _DROPGROUPCFG_INTERNALTYPE_DROP_BAG_LIST.oneofs_by_name['_drop_bag_id']
_DROPGROUPCFG_INTERNALTYPE_DROP_BAG_LIST.oneofs_by_name['_drop_bag_num'].fields.append(
  _DROPGROUPCFG_INTERNALTYPE_DROP_BAG_LIST.fields_by_name['drop_bag_num'])
_DROPGROUPCFG_INTERNALTYPE_DROP_BAG_LIST.fields_by_name['drop_bag_num'].containing_oneof = _DROPGROUPCFG_INTERNALTYPE_DROP_BAG_LIST.oneofs_by_name['_drop_bag_num']
_DROPGROUPCFG_INTERNALTYPE_DROP_BAG_LIST.oneofs_by_name['_drop_bag_percent'].fields.append(
  _DROPGROUPCFG_INTERNALTYPE_DROP_BAG_LIST.fields_by_name['drop_bag_percent'])
_DROPGROUPCFG_INTERNALTYPE_DROP_BAG_LIST.fields_by_name['drop_bag_percent'].containing_oneof = _DROPGROUPCFG_INTERNALTYPE_DROP_BAG_LIST.oneofs_by_name['_drop_bag_percent']
_DROPGROUPCFG.fields_by_name['drop_bag_list'].message_type = _DROPGROUPCFG_INTERNALTYPE_DROP_BAG_LIST
_DROPGROUPCFG.oneofs_by_name['_cfg_id'].fields.append(
  _DROPGROUPCFG.fields_by_name['cfg_id'])
_DROPGROUPCFG.fields_by_name['cfg_id'].containing_oneof = _DROPGROUPCFG.oneofs_by_name['_cfg_id']
_DROPGROUPCFG.oneofs_by_name['_name'].fields.append(
  _DROPGROUPCFG.fields_by_name['name'])
_DROPGROUPCFG.fields_by_name['name'].containing_oneof = _DROPGROUPCFG.oneofs_by_name['_name']
_DROPGROUPCFG.oneofs_by_name['_model_id'].fields.append(
  _DROPGROUPCFG.fields_by_name['model_id'])
_DROPGROUPCFG.fields_by_name['model_id'].containing_oneof = _DROPGROUPCFG.oneofs_by_name['_model_id']
_DROPGROUPCFG.oneofs_by_name['_pick_type'].fields.append(
  _DROPGROUPCFG.fields_by_name['pick_type'])
_DROPGROUPCFG.fields_by_name['pick_type'].containing_oneof = _DROPGROUPCFG.oneofs_by_name['_pick_type']
_DROPGROUPCFG.oneofs_by_name['_drop_type'].fields.append(
  _DROPGROUPCFG.fields_by_name['drop_type'])
_DROPGROUPCFG.fields_by_name['drop_type'].containing_oneof = _DROPGROUPCFG.oneofs_by_name['_drop_type']
_DROPGROUPCFGSHEET_ITEMDICENTRY.fields_by_name['value'].message_type = _DROPGROUPCFG
_DROPGROUPCFGSHEET_ITEMDICENTRY.containing_type = _DROPGROUPCFGSHEET
_DROPGROUPCFGSHEET.fields_by_name['item_dic'].message_type = _DROPGROUPCFGSHEET_ITEMDICENTRY
DESCRIPTOR.message_types_by_name['DropGroupCfg'] = _DROPGROUPCFG
DESCRIPTOR.message_types_by_name['DropGroupCfgSheet'] = _DROPGROUPCFGSHEET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DropGroupCfg = _reflection.GeneratedProtocolMessageType('DropGroupCfg', (_message.Message,), {

  'InternalType_drop_bag_list' : _reflection.GeneratedProtocolMessageType('InternalType_drop_bag_list', (_message.Message,), {
    'DESCRIPTOR' : _DROPGROUPCFG_INTERNALTYPE_DROP_BAG_LIST,
    '__module__' : 'dropgroup_pb2'
    # @@protoc_insertion_point(class_scope:DataConfig.DropGroupCfg.InternalType_drop_bag_list)
    })
  ,
  'DESCRIPTOR' : _DROPGROUPCFG,
  '__module__' : 'dropgroup_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.DropGroupCfg)
  })
_sym_db.RegisterMessage(DropGroupCfg)
_sym_db.RegisterMessage(DropGroupCfg.InternalType_drop_bag_list)

DropGroupCfgSheet = _reflection.GeneratedProtocolMessageType('DropGroupCfgSheet', (_message.Message,), {

  'ItemDicEntry' : _reflection.GeneratedProtocolMessageType('ItemDicEntry', (_message.Message,), {
    'DESCRIPTOR' : _DROPGROUPCFGSHEET_ITEMDICENTRY,
    '__module__' : 'dropgroup_pb2'
    # @@protoc_insertion_point(class_scope:DataConfig.DropGroupCfgSheet.ItemDicEntry)
    })
  ,
  'DESCRIPTOR' : _DROPGROUPCFGSHEET,
  '__module__' : 'dropgroup_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.DropGroupCfgSheet)
  })
_sym_db.RegisterMessage(DropGroupCfgSheet)
_sym_db.RegisterMessage(DropGroupCfgSheet.ItemDicEntry)


_DROPGROUPCFGSHEET_ITEMDICENTRY._options = None
# @@protoc_insertion_point(module_scope)
