# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dropbag.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dropbag.proto',
  package='DataConfig',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rdropbag.proto\x12\nDataConfig\"\xfa\x01\n\nDropBagCfg\x12\x13\n\x06\x63\x66g_id\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x18\n\x0b\x64rop_bag_id\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x11\n\x04name\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x16\n\tdrop_type\x18\x04 \x01(\rH\x03\x88\x01\x01\x12\x18\n\x0bprop_cfg_id\x18\x05 \x01(\rH\x04\x88\x01\x01\x12\x10\n\x03num\x18\x06 \x01(\rH\x05\x88\x01\x01\x12\x12\n\x05power\x18\x07 \x01(\x02H\x06\x88\x01\x01\x42\t\n\x07_cfg_idB\x0e\n\x0c_drop_bag_idB\x07\n\x05_nameB\x0c\n\n_drop_typeB\x0e\n\x0c_prop_cfg_idB\x06\n\x04_numB\x08\n\x06_power\"\x95\x01\n\x0f\x44ropBagCfgSheet\x12:\n\x08item_dic\x18\x01 \x03(\x0b\x32(.DataConfig.DropBagCfgSheet.ItemDicEntry\x1a\x46\n\x0cItemDicEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.DataConfig.DropBagCfg:\x02\x38\x01\x62\x06proto3'
)




_DROPBAGCFG = _descriptor.Descriptor(
  name='DropBagCfg',
  full_name='DataConfig.DropBagCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cfg_id', full_name='DataConfig.DropBagCfg.cfg_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='drop_bag_id', full_name='DataConfig.DropBagCfg.drop_bag_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='DataConfig.DropBagCfg.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='drop_type', full_name='DataConfig.DropBagCfg.drop_type', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prop_cfg_id', full_name='DataConfig.DropBagCfg.prop_cfg_id', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num', full_name='DataConfig.DropBagCfg.num', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='power', full_name='DataConfig.DropBagCfg.power', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_cfg_id', full_name='DataConfig.DropBagCfg._cfg_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_drop_bag_id', full_name='DataConfig.DropBagCfg._drop_bag_id',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_name', full_name='DataConfig.DropBagCfg._name',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_drop_type', full_name='DataConfig.DropBagCfg._drop_type',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_prop_cfg_id', full_name='DataConfig.DropBagCfg._prop_cfg_id',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_num', full_name='DataConfig.DropBagCfg._num',
      index=5, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_power', full_name='DataConfig.DropBagCfg._power',
      index=6, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=30,
  serialized_end=280,
)


_DROPBAGCFGSHEET_ITEMDICENTRY = _descriptor.Descriptor(
  name='ItemDicEntry',
  full_name='DataConfig.DropBagCfgSheet.ItemDicEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DataConfig.DropBagCfgSheet.ItemDicEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='DataConfig.DropBagCfgSheet.ItemDicEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=432,
)

_DROPBAGCFGSHEET = _descriptor.Descriptor(
  name='DropBagCfgSheet',
  full_name='DataConfig.DropBagCfgSheet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_dic', full_name='DataConfig.DropBagCfgSheet.item_dic', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DROPBAGCFGSHEET_ITEMDICENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=432,
)

_DROPBAGCFG.oneofs_by_name['_cfg_id'].fields.append(
  _DROPBAGCFG.fields_by_name['cfg_id'])
_DROPBAGCFG.fields_by_name['cfg_id'].containing_oneof = _DROPBAGCFG.oneofs_by_name['_cfg_id']
_DROPBAGCFG.oneofs_by_name['_drop_bag_id'].fields.append(
  _DROPBAGCFG.fields_by_name['drop_bag_id'])
_DROPBAGCFG.fields_by_name['drop_bag_id'].containing_oneof = _DROPBAGCFG.oneofs_by_name['_drop_bag_id']
_DROPBAGCFG.oneofs_by_name['_name'].fields.append(
  _DROPBAGCFG.fields_by_name['name'])
_DROPBAGCFG.fields_by_name['name'].containing_oneof = _DROPBAGCFG.oneofs_by_name['_name']
_DROPBAGCFG.oneofs_by_name['_drop_type'].fields.append(
  _DROPBAGCFG.fields_by_name['drop_type'])
_DROPBAGCFG.fields_by_name['drop_type'].containing_oneof = _DROPBAGCFG.oneofs_by_name['_drop_type']
_DROPBAGCFG.oneofs_by_name['_prop_cfg_id'].fields.append(
  _DROPBAGCFG.fields_by_name['prop_cfg_id'])
_DROPBAGCFG.fields_by_name['prop_cfg_id'].containing_oneof = _DROPBAGCFG.oneofs_by_name['_prop_cfg_id']
_DROPBAGCFG.oneofs_by_name['_num'].fields.append(
  _DROPBAGCFG.fields_by_name['num'])
_DROPBAGCFG.fields_by_name['num'].containing_oneof = _DROPBAGCFG.oneofs_by_name['_num']
_DROPBAGCFG.oneofs_by_name['_power'].fields.append(
  _DROPBAGCFG.fields_by_name['power'])
_DROPBAGCFG.fields_by_name['power'].containing_oneof = _DROPBAGCFG.oneofs_by_name['_power']
_DROPBAGCFGSHEET_ITEMDICENTRY.fields_by_name['value'].message_type = _DROPBAGCFG
_DROPBAGCFGSHEET_ITEMDICENTRY.containing_type = _DROPBAGCFGSHEET
_DROPBAGCFGSHEET.fields_by_name['item_dic'].message_type = _DROPBAGCFGSHEET_ITEMDICENTRY
DESCRIPTOR.message_types_by_name['DropBagCfg'] = _DROPBAGCFG
DESCRIPTOR.message_types_by_name['DropBagCfgSheet'] = _DROPBAGCFGSHEET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DropBagCfg = _reflection.GeneratedProtocolMessageType('DropBagCfg', (_message.Message,), {
  'DESCRIPTOR' : _DROPBAGCFG,
  '__module__' : 'dropbag_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.DropBagCfg)
  })
_sym_db.RegisterMessage(DropBagCfg)

DropBagCfgSheet = _reflection.GeneratedProtocolMessageType('DropBagCfgSheet', (_message.Message,), {

  'ItemDicEntry' : _reflection.GeneratedProtocolMessageType('ItemDicEntry', (_message.Message,), {
    'DESCRIPTOR' : _DROPBAGCFGSHEET_ITEMDICENTRY,
    '__module__' : 'dropbag_pb2'
    # @@protoc_insertion_point(class_scope:DataConfig.DropBagCfgSheet.ItemDicEntry)
    })
  ,
  'DESCRIPTOR' : _DROPBAGCFGSHEET,
  '__module__' : 'dropbag_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.DropBagCfgSheet)
  })
_sym_db.RegisterMessage(DropBagCfgSheet)
_sym_db.RegisterMessage(DropBagCfgSheet.ItemDicEntry)


_DROPBAGCFGSHEET_ITEMDICENTRY._options = None
# @@protoc_insertion_point(module_scope)
