# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: effect.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='effect.proto',
  package='DataConfig',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x65\x66\x66\x65\x63t.proto\x12\nDataConfig\"\xc1\x01\n\tEffectCfg\x12\x13\n\x06\x63\x66g_id\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x11\n\x04path\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x11\n\x04time\x18\x03 \x01(\x02H\x02\x88\x01\x01\x12\x11\n\x04loop\x18\x04 \x01(\x08H\x03\x88\x01\x01\x12\x16\n\tbind_type\x18\x05 \x01(\rH\x04\x88\x01\x01\x12\x11\n\x04temp\x18\x06 \x01(\x08H\x05\x88\x01\x01\x42\t\n\x07_cfg_idB\x07\n\x05_pathB\x07\n\x05_timeB\x07\n\x05_loopB\x0c\n\n_bind_typeB\x07\n\x05_temp\"\x92\x01\n\x0e\x45\x66\x66\x65\x63tCfgSheet\x12\x39\n\x08item_dic\x18\x01 \x03(\x0b\x32\'.DataConfig.EffectCfgSheet.ItemDicEntry\x1a\x45\n\x0cItemDicEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.DataConfig.EffectCfg:\x02\x38\x01\x62\x06proto3'
)




_EFFECTCFG = _descriptor.Descriptor(
  name='EffectCfg',
  full_name='DataConfig.EffectCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cfg_id', full_name='DataConfig.EffectCfg.cfg_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='path', full_name='DataConfig.EffectCfg.path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='DataConfig.EffectCfg.time', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='loop', full_name='DataConfig.EffectCfg.loop', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bind_type', full_name='DataConfig.EffectCfg.bind_type', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='temp', full_name='DataConfig.EffectCfg.temp', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_cfg_id', full_name='DataConfig.EffectCfg._cfg_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_path', full_name='DataConfig.EffectCfg._path',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_time', full_name='DataConfig.EffectCfg._time',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_loop', full_name='DataConfig.EffectCfg._loop',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_bind_type', full_name='DataConfig.EffectCfg._bind_type',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_temp', full_name='DataConfig.EffectCfg._temp',
      index=5, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=29,
  serialized_end=222,
)


_EFFECTCFGSHEET_ITEMDICENTRY = _descriptor.Descriptor(
  name='ItemDicEntry',
  full_name='DataConfig.EffectCfgSheet.ItemDicEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DataConfig.EffectCfgSheet.ItemDicEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='DataConfig.EffectCfgSheet.ItemDicEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=371,
)

_EFFECTCFGSHEET = _descriptor.Descriptor(
  name='EffectCfgSheet',
  full_name='DataConfig.EffectCfgSheet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_dic', full_name='DataConfig.EffectCfgSheet.item_dic', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_EFFECTCFGSHEET_ITEMDICENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=371,
)

_EFFECTCFG.oneofs_by_name['_cfg_id'].fields.append(
  _EFFECTCFG.fields_by_name['cfg_id'])
_EFFECTCFG.fields_by_name['cfg_id'].containing_oneof = _EFFECTCFG.oneofs_by_name['_cfg_id']
_EFFECTCFG.oneofs_by_name['_path'].fields.append(
  _EFFECTCFG.fields_by_name['path'])
_EFFECTCFG.fields_by_name['path'].containing_oneof = _EFFECTCFG.oneofs_by_name['_path']
_EFFECTCFG.oneofs_by_name['_time'].fields.append(
  _EFFECTCFG.fields_by_name['time'])
_EFFECTCFG.fields_by_name['time'].containing_oneof = _EFFECTCFG.oneofs_by_name['_time']
_EFFECTCFG.oneofs_by_name['_loop'].fields.append(
  _EFFECTCFG.fields_by_name['loop'])
_EFFECTCFG.fields_by_name['loop'].containing_oneof = _EFFECTCFG.oneofs_by_name['_loop']
_EFFECTCFG.oneofs_by_name['_bind_type'].fields.append(
  _EFFECTCFG.fields_by_name['bind_type'])
_EFFECTCFG.fields_by_name['bind_type'].containing_oneof = _EFFECTCFG.oneofs_by_name['_bind_type']
_EFFECTCFG.oneofs_by_name['_temp'].fields.append(
  _EFFECTCFG.fields_by_name['temp'])
_EFFECTCFG.fields_by_name['temp'].containing_oneof = _EFFECTCFG.oneofs_by_name['_temp']
_EFFECTCFGSHEET_ITEMDICENTRY.fields_by_name['value'].message_type = _EFFECTCFG
_EFFECTCFGSHEET_ITEMDICENTRY.containing_type = _EFFECTCFGSHEET
_EFFECTCFGSHEET.fields_by_name['item_dic'].message_type = _EFFECTCFGSHEET_ITEMDICENTRY
DESCRIPTOR.message_types_by_name['EffectCfg'] = _EFFECTCFG
DESCRIPTOR.message_types_by_name['EffectCfgSheet'] = _EFFECTCFGSHEET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EffectCfg = _reflection.GeneratedProtocolMessageType('EffectCfg', (_message.Message,), {
  'DESCRIPTOR' : _EFFECTCFG,
  '__module__' : 'effect_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.EffectCfg)
  })
_sym_db.RegisterMessage(EffectCfg)

EffectCfgSheet = _reflection.GeneratedProtocolMessageType('EffectCfgSheet', (_message.Message,), {

  'ItemDicEntry' : _reflection.GeneratedProtocolMessageType('ItemDicEntry', (_message.Message,), {
    'DESCRIPTOR' : _EFFECTCFGSHEET_ITEMDICENTRY,
    '__module__' : 'effect_pb2'
    # @@protoc_insertion_point(class_scope:DataConfig.EffectCfgSheet.ItemDicEntry)
    })
  ,
  'DESCRIPTOR' : _EFFECTCFGSHEET,
  '__module__' : 'effect_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.EffectCfgSheet)
  })
_sym_db.RegisterMessage(EffectCfgSheet)
_sym_db.RegisterMessage(EffectCfgSheet.ItemDicEntry)


_EFFECTCFGSHEET_ITEMDICENTRY._options = None
# @@protoc_insertion_point(module_scope)
