# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='event.proto',
  package='DataConfig',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x65vent.proto\x12\nDataConfig\"F\n\x08\x45ventCfg\x12\x13\n\x06\x63\x66g_id\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x11\n\x04name\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\t\n\x07_cfg_idB\x07\n\x05_name\"\x8f\x01\n\rEventCfgSheet\x12\x38\n\x08item_dic\x18\x01 \x03(\x0b\x32&.DataConfig.EventCfgSheet.ItemDicEntry\x1a\x44\n\x0cItemDicEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.DataConfig.EventCfg:\x02\x38\x01\x62\x06proto3'
)




_EVENTCFG = _descriptor.Descriptor(
  name='EventCfg',
  full_name='DataConfig.EventCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cfg_id', full_name='DataConfig.EventCfg.cfg_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='DataConfig.EventCfg.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_cfg_id', full_name='DataConfig.EventCfg._cfg_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_name', full_name='DataConfig.EventCfg._name',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=27,
  serialized_end=97,
)


_EVENTCFGSHEET_ITEMDICENTRY = _descriptor.Descriptor(
  name='ItemDicEntry',
  full_name='DataConfig.EventCfgSheet.ItemDicEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DataConfig.EventCfgSheet.ItemDicEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='DataConfig.EventCfgSheet.ItemDicEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=243,
)

_EVENTCFGSHEET = _descriptor.Descriptor(
  name='EventCfgSheet',
  full_name='DataConfig.EventCfgSheet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_dic', full_name='DataConfig.EventCfgSheet.item_dic', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_EVENTCFGSHEET_ITEMDICENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=243,
)

_EVENTCFG.oneofs_by_name['_cfg_id'].fields.append(
  _EVENTCFG.fields_by_name['cfg_id'])
_EVENTCFG.fields_by_name['cfg_id'].containing_oneof = _EVENTCFG.oneofs_by_name['_cfg_id']
_EVENTCFG.oneofs_by_name['_name'].fields.append(
  _EVENTCFG.fields_by_name['name'])
_EVENTCFG.fields_by_name['name'].containing_oneof = _EVENTCFG.oneofs_by_name['_name']
_EVENTCFGSHEET_ITEMDICENTRY.fields_by_name['value'].message_type = _EVENTCFG
_EVENTCFGSHEET_ITEMDICENTRY.containing_type = _EVENTCFGSHEET
_EVENTCFGSHEET.fields_by_name['item_dic'].message_type = _EVENTCFGSHEET_ITEMDICENTRY
DESCRIPTOR.message_types_by_name['EventCfg'] = _EVENTCFG
DESCRIPTOR.message_types_by_name['EventCfgSheet'] = _EVENTCFGSHEET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EventCfg = _reflection.GeneratedProtocolMessageType('EventCfg', (_message.Message,), {
  'DESCRIPTOR' : _EVENTCFG,
  '__module__' : 'event_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.EventCfg)
  })
_sym_db.RegisterMessage(EventCfg)

EventCfgSheet = _reflection.GeneratedProtocolMessageType('EventCfgSheet', (_message.Message,), {

  'ItemDicEntry' : _reflection.GeneratedProtocolMessageType('ItemDicEntry', (_message.Message,), {
    'DESCRIPTOR' : _EVENTCFGSHEET_ITEMDICENTRY,
    '__module__' : 'event_pb2'
    # @@protoc_insertion_point(class_scope:DataConfig.EventCfgSheet.ItemDicEntry)
    })
  ,
  'DESCRIPTOR' : _EVENTCFGSHEET,
  '__module__' : 'event_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.EventCfgSheet)
  })
_sym_db.RegisterMessage(EventCfgSheet)
_sym_db.RegisterMessage(EventCfgSheet.ItemDicEntry)


_EVENTCFGSHEET_ITEMDICENTRY._options = None
# @@protoc_insertion_point(module_scope)
