# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: global.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='global.proto',
  package='DataConfig',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cglobal.proto\x12\nDataConfig\"\xa1\x01\n\tGlobalCfg\x12\x13\n\x06\x63\x66g_id\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x16\n\tvalue_int\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x18\n\x0bvalue_float\x18\x03 \x01(\x02H\x02\x88\x01\x01\x12\x16\n\tvalue_str\x18\x04 \x01(\tH\x03\x88\x01\x01\x42\t\n\x07_cfg_idB\x0c\n\n_value_intB\x0e\n\x0c_value_floatB\x0c\n\n_value_str\"\x92\x01\n\x0eGlobalCfgSheet\x12\x39\n\x08item_dic\x18\x01 \x03(\x0b\x32\'.DataConfig.GlobalCfgSheet.ItemDicEntry\x1a\x45\n\x0cItemDicEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.DataConfig.GlobalCfg:\x02\x38\x01\x62\x06proto3'
)




_GLOBALCFG = _descriptor.Descriptor(
  name='GlobalCfg',
  full_name='DataConfig.GlobalCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cfg_id', full_name='DataConfig.GlobalCfg.cfg_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value_int', full_name='DataConfig.GlobalCfg.value_int', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value_float', full_name='DataConfig.GlobalCfg.value_float', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value_str', full_name='DataConfig.GlobalCfg.value_str', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_cfg_id', full_name='DataConfig.GlobalCfg._cfg_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_value_int', full_name='DataConfig.GlobalCfg._value_int',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_value_float', full_name='DataConfig.GlobalCfg._value_float',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_value_str', full_name='DataConfig.GlobalCfg._value_str',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=29,
  serialized_end=190,
)


_GLOBALCFGSHEET_ITEMDICENTRY = _descriptor.Descriptor(
  name='ItemDicEntry',
  full_name='DataConfig.GlobalCfgSheet.ItemDicEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DataConfig.GlobalCfgSheet.ItemDicEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='DataConfig.GlobalCfgSheet.ItemDicEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=339,
)

_GLOBALCFGSHEET = _descriptor.Descriptor(
  name='GlobalCfgSheet',
  full_name='DataConfig.GlobalCfgSheet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_dic', full_name='DataConfig.GlobalCfgSheet.item_dic', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GLOBALCFGSHEET_ITEMDICENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=339,
)

_GLOBALCFG.oneofs_by_name['_cfg_id'].fields.append(
  _GLOBALCFG.fields_by_name['cfg_id'])
_GLOBALCFG.fields_by_name['cfg_id'].containing_oneof = _GLOBALCFG.oneofs_by_name['_cfg_id']
_GLOBALCFG.oneofs_by_name['_value_int'].fields.append(
  _GLOBALCFG.fields_by_name['value_int'])
_GLOBALCFG.fields_by_name['value_int'].containing_oneof = _GLOBALCFG.oneofs_by_name['_value_int']
_GLOBALCFG.oneofs_by_name['_value_float'].fields.append(
  _GLOBALCFG.fields_by_name['value_float'])
_GLOBALCFG.fields_by_name['value_float'].containing_oneof = _GLOBALCFG.oneofs_by_name['_value_float']
_GLOBALCFG.oneofs_by_name['_value_str'].fields.append(
  _GLOBALCFG.fields_by_name['value_str'])
_GLOBALCFG.fields_by_name['value_str'].containing_oneof = _GLOBALCFG.oneofs_by_name['_value_str']
_GLOBALCFGSHEET_ITEMDICENTRY.fields_by_name['value'].message_type = _GLOBALCFG
_GLOBALCFGSHEET_ITEMDICENTRY.containing_type = _GLOBALCFGSHEET
_GLOBALCFGSHEET.fields_by_name['item_dic'].message_type = _GLOBALCFGSHEET_ITEMDICENTRY
DESCRIPTOR.message_types_by_name['GlobalCfg'] = _GLOBALCFG
DESCRIPTOR.message_types_by_name['GlobalCfgSheet'] = _GLOBALCFGSHEET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GlobalCfg = _reflection.GeneratedProtocolMessageType('GlobalCfg', (_message.Message,), {
  'DESCRIPTOR' : _GLOBALCFG,
  '__module__' : 'global_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.GlobalCfg)
  })
_sym_db.RegisterMessage(GlobalCfg)

GlobalCfgSheet = _reflection.GeneratedProtocolMessageType('GlobalCfgSheet', (_message.Message,), {

  'ItemDicEntry' : _reflection.GeneratedProtocolMessageType('ItemDicEntry', (_message.Message,), {
    'DESCRIPTOR' : _GLOBALCFGSHEET_ITEMDICENTRY,
    '__module__' : 'global_pb2'
    # @@protoc_insertion_point(class_scope:DataConfig.GlobalCfgSheet.ItemDicEntry)
    })
  ,
  'DESCRIPTOR' : _GLOBALCFGSHEET,
  '__module__' : 'global_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.GlobalCfgSheet)
  })
_sym_db.RegisterMessage(GlobalCfgSheet)
_sym_db.RegisterMessage(GlobalCfgSheet.ItemDicEntry)


_GLOBALCFGSHEET_ITEMDICENTRY._options = None
# @@protoc_insertion_point(module_scope)
