# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: level.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='level.proto',
  package='DataConfig',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0blevel.proto\x12\nDataConfig\"\xc0\x01\n\x08LevelCfg\x12\x13\n\x06\x63\x66g_id\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x11\n\x04path\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x11\n\x04name\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x1f\n\x12is_streaming_world\x18\x04 \x01(\x08H\x03\x88\x01\x01\x12\x16\n\tfold_name\x18\x05 \x01(\tH\x04\x88\x01\x01\x42\t\n\x07_cfg_idB\x07\n\x05_pathB\x07\n\x05_nameB\x15\n\x13_is_streaming_worldB\x0c\n\n_fold_name\"\x8f\x01\n\rLevelCfgSheet\x12\x38\n\x08item_dic\x18\x01 \x03(\x0b\x32&.DataConfig.LevelCfgSheet.ItemDicEntry\x1a\x44\n\x0cItemDicEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.DataConfig.LevelCfg:\x02\x38\x01\x62\x06proto3'
)




_LEVELCFG = _descriptor.Descriptor(
  name='LevelCfg',
  full_name='DataConfig.LevelCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cfg_id', full_name='DataConfig.LevelCfg.cfg_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='path', full_name='DataConfig.LevelCfg.path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='DataConfig.LevelCfg.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_streaming_world', full_name='DataConfig.LevelCfg.is_streaming_world', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fold_name', full_name='DataConfig.LevelCfg.fold_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_cfg_id', full_name='DataConfig.LevelCfg._cfg_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_path', full_name='DataConfig.LevelCfg._path',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_name', full_name='DataConfig.LevelCfg._name',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_is_streaming_world', full_name='DataConfig.LevelCfg._is_streaming_world',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_fold_name', full_name='DataConfig.LevelCfg._fold_name',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=28,
  serialized_end=220,
)


_LEVELCFGSHEET_ITEMDICENTRY = _descriptor.Descriptor(
  name='ItemDicEntry',
  full_name='DataConfig.LevelCfgSheet.ItemDicEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DataConfig.LevelCfgSheet.ItemDicEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='DataConfig.LevelCfgSheet.ItemDicEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=298,
  serialized_end=366,
)

_LEVELCFGSHEET = _descriptor.Descriptor(
  name='LevelCfgSheet',
  full_name='DataConfig.LevelCfgSheet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_dic', full_name='DataConfig.LevelCfgSheet.item_dic', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_LEVELCFGSHEET_ITEMDICENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=366,
)

_LEVELCFG.oneofs_by_name['_cfg_id'].fields.append(
  _LEVELCFG.fields_by_name['cfg_id'])
_LEVELCFG.fields_by_name['cfg_id'].containing_oneof = _LEVELCFG.oneofs_by_name['_cfg_id']
_LEVELCFG.oneofs_by_name['_path'].fields.append(
  _LEVELCFG.fields_by_name['path'])
_LEVELCFG.fields_by_name['path'].containing_oneof = _LEVELCFG.oneofs_by_name['_path']
_LEVELCFG.oneofs_by_name['_name'].fields.append(
  _LEVELCFG.fields_by_name['name'])
_LEVELCFG.fields_by_name['name'].containing_oneof = _LEVELCFG.oneofs_by_name['_name']
_LEVELCFG.oneofs_by_name['_is_streaming_world'].fields.append(
  _LEVELCFG.fields_by_name['is_streaming_world'])
_LEVELCFG.fields_by_name['is_streaming_world'].containing_oneof = _LEVELCFG.oneofs_by_name['_is_streaming_world']
_LEVELCFG.oneofs_by_name['_fold_name'].fields.append(
  _LEVELCFG.fields_by_name['fold_name'])
_LEVELCFG.fields_by_name['fold_name'].containing_oneof = _LEVELCFG.oneofs_by_name['_fold_name']
_LEVELCFGSHEET_ITEMDICENTRY.fields_by_name['value'].message_type = _LEVELCFG
_LEVELCFGSHEET_ITEMDICENTRY.containing_type = _LEVELCFGSHEET
_LEVELCFGSHEET.fields_by_name['item_dic'].message_type = _LEVELCFGSHEET_ITEMDICENTRY
DESCRIPTOR.message_types_by_name['LevelCfg'] = _LEVELCFG
DESCRIPTOR.message_types_by_name['LevelCfgSheet'] = _LEVELCFGSHEET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LevelCfg = _reflection.GeneratedProtocolMessageType('LevelCfg', (_message.Message,), {
  'DESCRIPTOR' : _LEVELCFG,
  '__module__' : 'level_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.LevelCfg)
  })
_sym_db.RegisterMessage(LevelCfg)

LevelCfgSheet = _reflection.GeneratedProtocolMessageType('LevelCfgSheet', (_message.Message,), {

  'ItemDicEntry' : _reflection.GeneratedProtocolMessageType('ItemDicEntry', (_message.Message,), {
    'DESCRIPTOR' : _LEVELCFGSHEET_ITEMDICENTRY,
    '__module__' : 'level_pb2'
    # @@protoc_insertion_point(class_scope:DataConfig.LevelCfgSheet.ItemDicEntry)
    })
  ,
  'DESCRIPTOR' : _LEVELCFGSHEET,
  '__module__' : 'level_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.LevelCfgSheet)
  })
_sym_db.RegisterMessage(LevelCfgSheet)
_sym_db.RegisterMessage(LevelCfgSheet.ItemDicEntry)


_LEVELCFGSHEET_ITEMDICENTRY._options = None
# @@protoc_insertion_point(module_scope)
