# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='model.proto',
  package='DataConfig',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bmodel.proto\x12\nDataConfig\"\xba\x01\n\x08ModelCfg\x12\x13\n\x06\x63\x66g_id\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x17\n\nmodel_name\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x17\n\nmodel_type\x18\x03 \x01(\x05H\x02\x88\x01\x01\x12\x13\n\x06height\x18\x04 \x01(\x02H\x03\x88\x01\x01\x12\x13\n\x06radius\x18\x05 \x01(\x02H\x04\x88\x01\x01\x42\t\n\x07_cfg_idB\r\n\x0b_model_nameB\r\n\x0b_model_typeB\t\n\x07_heightB\t\n\x07_radius\"\x8f\x01\n\rModelCfgSheet\x12\x38\n\x08item_dic\x18\x01 \x03(\x0b\x32&.DataConfig.ModelCfgSheet.ItemDicEntry\x1a\x44\n\x0cItemDicEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.DataConfig.ModelCfg:\x02\x38\x01\x62\x06proto3'
)




_MODELCFG = _descriptor.Descriptor(
  name='ModelCfg',
  full_name='DataConfig.ModelCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cfg_id', full_name='DataConfig.ModelCfg.cfg_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_name', full_name='DataConfig.ModelCfg.model_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_type', full_name='DataConfig.ModelCfg.model_type', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='DataConfig.ModelCfg.height', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='radius', full_name='DataConfig.ModelCfg.radius', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_cfg_id', full_name='DataConfig.ModelCfg._cfg_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_model_name', full_name='DataConfig.ModelCfg._model_name',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_model_type', full_name='DataConfig.ModelCfg._model_type',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_height', full_name='DataConfig.ModelCfg._height',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_radius', full_name='DataConfig.ModelCfg._radius',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=28,
  serialized_end=214,
)


_MODELCFGSHEET_ITEMDICENTRY = _descriptor.Descriptor(
  name='ItemDicEntry',
  full_name='DataConfig.ModelCfgSheet.ItemDicEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DataConfig.ModelCfgSheet.ItemDicEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='DataConfig.ModelCfgSheet.ItemDicEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=292,
  serialized_end=360,
)

_MODELCFGSHEET = _descriptor.Descriptor(
  name='ModelCfgSheet',
  full_name='DataConfig.ModelCfgSheet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_dic', full_name='DataConfig.ModelCfgSheet.item_dic', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_MODELCFGSHEET_ITEMDICENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=360,
)

_MODELCFG.oneofs_by_name['_cfg_id'].fields.append(
  _MODELCFG.fields_by_name['cfg_id'])
_MODELCFG.fields_by_name['cfg_id'].containing_oneof = _MODELCFG.oneofs_by_name['_cfg_id']
_MODELCFG.oneofs_by_name['_model_name'].fields.append(
  _MODELCFG.fields_by_name['model_name'])
_MODELCFG.fields_by_name['model_name'].containing_oneof = _MODELCFG.oneofs_by_name['_model_name']
_MODELCFG.oneofs_by_name['_model_type'].fields.append(
  _MODELCFG.fields_by_name['model_type'])
_MODELCFG.fields_by_name['model_type'].containing_oneof = _MODELCFG.oneofs_by_name['_model_type']
_MODELCFG.oneofs_by_name['_height'].fields.append(
  _MODELCFG.fields_by_name['height'])
_MODELCFG.fields_by_name['height'].containing_oneof = _MODELCFG.oneofs_by_name['_height']
_MODELCFG.oneofs_by_name['_radius'].fields.append(
  _MODELCFG.fields_by_name['radius'])
_MODELCFG.fields_by_name['radius'].containing_oneof = _MODELCFG.oneofs_by_name['_radius']
_MODELCFGSHEET_ITEMDICENTRY.fields_by_name['value'].message_type = _MODELCFG
_MODELCFGSHEET_ITEMDICENTRY.containing_type = _MODELCFGSHEET
_MODELCFGSHEET.fields_by_name['item_dic'].message_type = _MODELCFGSHEET_ITEMDICENTRY
DESCRIPTOR.message_types_by_name['ModelCfg'] = _MODELCFG
DESCRIPTOR.message_types_by_name['ModelCfgSheet'] = _MODELCFGSHEET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelCfg = _reflection.GeneratedProtocolMessageType('ModelCfg', (_message.Message,), {
  'DESCRIPTOR' : _MODELCFG,
  '__module__' : 'model_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.ModelCfg)
  })
_sym_db.RegisterMessage(ModelCfg)

ModelCfgSheet = _reflection.GeneratedProtocolMessageType('ModelCfgSheet', (_message.Message,), {

  'ItemDicEntry' : _reflection.GeneratedProtocolMessageType('ItemDicEntry', (_message.Message,), {
    'DESCRIPTOR' : _MODELCFGSHEET_ITEMDICENTRY,
    '__module__' : 'model_pb2'
    # @@protoc_insertion_point(class_scope:DataConfig.ModelCfgSheet.ItemDicEntry)
    })
  ,
  'DESCRIPTOR' : _MODELCFGSHEET,
  '__module__' : 'model_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.ModelCfgSheet)
  })
_sym_db.RegisterMessage(ModelCfgSheet)
_sym_db.RegisterMessage(ModelCfgSheet.ItemDicEntry)


_MODELCFGSHEET_ITEMDICENTRY._options = None
# @@protoc_insertion_point(module_scope)
