# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: npcmettle.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='npcmettle.proto',
  package='DataConfig',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fnpcmettle.proto\x12\nDataConfig\"t\n\x0cNpcMettleCfg\x12\x13\n\x06\x63\x66g_id\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x18\n\x0bmettle_type\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x11\n\x04note\x18\x03 \x01(\tH\x02\x88\x01\x01\x42\t\n\x07_cfg_idB\x0e\n\x0c_mettle_typeB\x07\n\x05_note\"\x9b\x01\n\x11NpcMettleCfgSheet\x12<\n\x08item_dic\x18\x01 \x03(\x0b\x32*.DataConfig.NpcMettleCfgSheet.ItemDicEntry\x1aH\n\x0cItemDicEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.DataConfig.NpcMettleCfg:\x02\x38\x01\x62\x06proto3'
)




_NPCMETTLECFG = _descriptor.Descriptor(
  name='NpcMettleCfg',
  full_name='DataConfig.NpcMettleCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cfg_id', full_name='DataConfig.NpcMettleCfg.cfg_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mettle_type', full_name='DataConfig.NpcMettleCfg.mettle_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='note', full_name='DataConfig.NpcMettleCfg.note', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_cfg_id', full_name='DataConfig.NpcMettleCfg._cfg_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_mettle_type', full_name='DataConfig.NpcMettleCfg._mettle_type',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_note', full_name='DataConfig.NpcMettleCfg._note',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=31,
  serialized_end=147,
)


_NPCMETTLECFGSHEET_ITEMDICENTRY = _descriptor.Descriptor(
  name='ItemDicEntry',
  full_name='DataConfig.NpcMettleCfgSheet.ItemDicEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DataConfig.NpcMettleCfgSheet.ItemDicEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='DataConfig.NpcMettleCfgSheet.ItemDicEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=305,
)

_NPCMETTLECFGSHEET = _descriptor.Descriptor(
  name='NpcMettleCfgSheet',
  full_name='DataConfig.NpcMettleCfgSheet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_dic', full_name='DataConfig.NpcMettleCfgSheet.item_dic', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_NPCMETTLECFGSHEET_ITEMDICENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=305,
)

_NPCMETTLECFG.oneofs_by_name['_cfg_id'].fields.append(
  _NPCMETTLECFG.fields_by_name['cfg_id'])
_NPCMETTLECFG.fields_by_name['cfg_id'].containing_oneof = _NPCMETTLECFG.oneofs_by_name['_cfg_id']
_NPCMETTLECFG.oneofs_by_name['_mettle_type'].fields.append(
  _NPCMETTLECFG.fields_by_name['mettle_type'])
_NPCMETTLECFG.fields_by_name['mettle_type'].containing_oneof = _NPCMETTLECFG.oneofs_by_name['_mettle_type']
_NPCMETTLECFG.oneofs_by_name['_note'].fields.append(
  _NPCMETTLECFG.fields_by_name['note'])
_NPCMETTLECFG.fields_by_name['note'].containing_oneof = _NPCMETTLECFG.oneofs_by_name['_note']
_NPCMETTLECFGSHEET_ITEMDICENTRY.fields_by_name['value'].message_type = _NPCMETTLECFG
_NPCMETTLECFGSHEET_ITEMDICENTRY.containing_type = _NPCMETTLECFGSHEET
_NPCMETTLECFGSHEET.fields_by_name['item_dic'].message_type = _NPCMETTLECFGSHEET_ITEMDICENTRY
DESCRIPTOR.message_types_by_name['NpcMettleCfg'] = _NPCMETTLECFG
DESCRIPTOR.message_types_by_name['NpcMettleCfgSheet'] = _NPCMETTLECFGSHEET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NpcMettleCfg = _reflection.GeneratedProtocolMessageType('NpcMettleCfg', (_message.Message,), {
  'DESCRIPTOR' : _NPCMETTLECFG,
  '__module__' : 'npcmettle_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.NpcMettleCfg)
  })
_sym_db.RegisterMessage(NpcMettleCfg)

NpcMettleCfgSheet = _reflection.GeneratedProtocolMessageType('NpcMettleCfgSheet', (_message.Message,), {

  'ItemDicEntry' : _reflection.GeneratedProtocolMessageType('ItemDicEntry', (_message.Message,), {
    'DESCRIPTOR' : _NPCMETTLECFGSHEET_ITEMDICENTRY,
    '__module__' : 'npcmettle_pb2'
    # @@protoc_insertion_point(class_scope:DataConfig.NpcMettleCfgSheet.ItemDicEntry)
    })
  ,
  'DESCRIPTOR' : _NPCMETTLECFGSHEET,
  '__module__' : 'npcmettle_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.NpcMettleCfgSheet)
  })
_sym_db.RegisterMessage(NpcMettleCfgSheet)
_sym_db.RegisterMessage(NpcMettleCfgSheet.ItemDicEntry)


_NPCMETTLECFGSHEET_ITEMDICENTRY._options = None
# @@protoc_insertion_point(module_scope)
