# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: propprobability.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='propprobability.proto',
  package='DataConfig',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15propprobability.proto\x12\nDataConfig\"\x9a\x02\n\x12PropProbabilityCfg\x12\x14\n\x07prop_id\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x16\n\tpb1_value\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x16\n\tpb2_value\x18\x03 \x01(\rH\x02\x88\x01\x01\x12\x16\n\tpb3_value\x18\x04 \x01(\rH\x03\x88\x01\x01\x12\x16\n\tpb4_value\x18\x05 \x01(\rH\x04\x88\x01\x01\x12\x16\n\tpb5_value\x18\x06 \x01(\rH\x05\x88\x01\x01\x12\x16\n\tpb6_value\x18\x07 \x01(\rH\x06\x88\x01\x01\x42\n\n\x08_prop_idB\x0c\n\n_pb1_valueB\x0c\n\n_pb2_valueB\x0c\n\n_pb3_valueB\x0c\n\n_pb4_valueB\x0c\n\n_pb5_valueB\x0c\n\n_pb6_value\"\xad\x01\n\x17PropProbabilityCfgSheet\x12\x42\n\x08item_dic\x18\x01 \x03(\x0b\x32\x30.DataConfig.PropProbabilityCfgSheet.ItemDicEntry\x1aN\n\x0cItemDicEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12-\n\x05value\x18\x02 \x01(\x0b\x32\x1e.DataConfig.PropProbabilityCfg:\x02\x38\x01\x62\x06proto3'
)




_PROPPROBABILITYCFG = _descriptor.Descriptor(
  name='PropProbabilityCfg',
  full_name='DataConfig.PropProbabilityCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='prop_id', full_name='DataConfig.PropProbabilityCfg.prop_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pb1_value', full_name='DataConfig.PropProbabilityCfg.pb1_value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pb2_value', full_name='DataConfig.PropProbabilityCfg.pb2_value', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pb3_value', full_name='DataConfig.PropProbabilityCfg.pb3_value', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pb4_value', full_name='DataConfig.PropProbabilityCfg.pb4_value', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pb5_value', full_name='DataConfig.PropProbabilityCfg.pb5_value', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pb6_value', full_name='DataConfig.PropProbabilityCfg.pb6_value', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_prop_id', full_name='DataConfig.PropProbabilityCfg._prop_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_pb1_value', full_name='DataConfig.PropProbabilityCfg._pb1_value',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_pb2_value', full_name='DataConfig.PropProbabilityCfg._pb2_value',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_pb3_value', full_name='DataConfig.PropProbabilityCfg._pb3_value',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_pb4_value', full_name='DataConfig.PropProbabilityCfg._pb4_value',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_pb5_value', full_name='DataConfig.PropProbabilityCfg._pb5_value',
      index=5, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_pb6_value', full_name='DataConfig.PropProbabilityCfg._pb6_value',
      index=6, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=38,
  serialized_end=320,
)


_PROPPROBABILITYCFGSHEET_ITEMDICENTRY = _descriptor.Descriptor(
  name='ItemDicEntry',
  full_name='DataConfig.PropProbabilityCfgSheet.ItemDicEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DataConfig.PropProbabilityCfgSheet.ItemDicEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='DataConfig.PropProbabilityCfgSheet.ItemDicEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=496,
)

_PROPPROBABILITYCFGSHEET = _descriptor.Descriptor(
  name='PropProbabilityCfgSheet',
  full_name='DataConfig.PropProbabilityCfgSheet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_dic', full_name='DataConfig.PropProbabilityCfgSheet.item_dic', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PROPPROBABILITYCFGSHEET_ITEMDICENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=496,
)

_PROPPROBABILITYCFG.oneofs_by_name['_prop_id'].fields.append(
  _PROPPROBABILITYCFG.fields_by_name['prop_id'])
_PROPPROBABILITYCFG.fields_by_name['prop_id'].containing_oneof = _PROPPROBABILITYCFG.oneofs_by_name['_prop_id']
_PROPPROBABILITYCFG.oneofs_by_name['_pb1_value'].fields.append(
  _PROPPROBABILITYCFG.fields_by_name['pb1_value'])
_PROPPROBABILITYCFG.fields_by_name['pb1_value'].containing_oneof = _PROPPROBABILITYCFG.oneofs_by_name['_pb1_value']
_PROPPROBABILITYCFG.oneofs_by_name['_pb2_value'].fields.append(
  _PROPPROBABILITYCFG.fields_by_name['pb2_value'])
_PROPPROBABILITYCFG.fields_by_name['pb2_value'].containing_oneof = _PROPPROBABILITYCFG.oneofs_by_name['_pb2_value']
_PROPPROBABILITYCFG.oneofs_by_name['_pb3_value'].fields.append(
  _PROPPROBABILITYCFG.fields_by_name['pb3_value'])
_PROPPROBABILITYCFG.fields_by_name['pb3_value'].containing_oneof = _PROPPROBABILITYCFG.oneofs_by_name['_pb3_value']
_PROPPROBABILITYCFG.oneofs_by_name['_pb4_value'].fields.append(
  _PROPPROBABILITYCFG.fields_by_name['pb4_value'])
_PROPPROBABILITYCFG.fields_by_name['pb4_value'].containing_oneof = _PROPPROBABILITYCFG.oneofs_by_name['_pb4_value']
_PROPPROBABILITYCFG.oneofs_by_name['_pb5_value'].fields.append(
  _PROPPROBABILITYCFG.fields_by_name['pb5_value'])
_PROPPROBABILITYCFG.fields_by_name['pb5_value'].containing_oneof = _PROPPROBABILITYCFG.oneofs_by_name['_pb5_value']
_PROPPROBABILITYCFG.oneofs_by_name['_pb6_value'].fields.append(
  _PROPPROBABILITYCFG.fields_by_name['pb6_value'])
_PROPPROBABILITYCFG.fields_by_name['pb6_value'].containing_oneof = _PROPPROBABILITYCFG.oneofs_by_name['_pb6_value']
_PROPPROBABILITYCFGSHEET_ITEMDICENTRY.fields_by_name['value'].message_type = _PROPPROBABILITYCFG
_PROPPROBABILITYCFGSHEET_ITEMDICENTRY.containing_type = _PROPPROBABILITYCFGSHEET
_PROPPROBABILITYCFGSHEET.fields_by_name['item_dic'].message_type = _PROPPROBABILITYCFGSHEET_ITEMDICENTRY
DESCRIPTOR.message_types_by_name['PropProbabilityCfg'] = _PROPPROBABILITYCFG
DESCRIPTOR.message_types_by_name['PropProbabilityCfgSheet'] = _PROPPROBABILITYCFGSHEET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PropProbabilityCfg = _reflection.GeneratedProtocolMessageType('PropProbabilityCfg', (_message.Message,), {
  'DESCRIPTOR' : _PROPPROBABILITYCFG,
  '__module__' : 'propprobability_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.PropProbabilityCfg)
  })
_sym_db.RegisterMessage(PropProbabilityCfg)

PropProbabilityCfgSheet = _reflection.GeneratedProtocolMessageType('PropProbabilityCfgSheet', (_message.Message,), {

  'ItemDicEntry' : _reflection.GeneratedProtocolMessageType('ItemDicEntry', (_message.Message,), {
    'DESCRIPTOR' : _PROPPROBABILITYCFGSHEET_ITEMDICENTRY,
    '__module__' : 'propprobability_pb2'
    # @@protoc_insertion_point(class_scope:DataConfig.PropProbabilityCfgSheet.ItemDicEntry)
    })
  ,
  'DESCRIPTOR' : _PROPPROBABILITYCFGSHEET,
  '__module__' : 'propprobability_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.PropProbabilityCfgSheet)
  })
_sym_db.RegisterMessage(PropProbabilityCfgSheet)
_sym_db.RegisterMessage(PropProbabilityCfgSheet.ItemDicEntry)


_PROPPROBABILITYCFGSHEET_ITEMDICENTRY._options = None
# @@protoc_insertion_point(module_scope)
