# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: property.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='property.proto',
  package='DataConfig',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eproperty.proto\x12\nDataConfig\"\xb5\x01\n\x0bPropertyCfg\x12\x1a\n\rNPCPropertyID\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x18\n\x0bNPCProperty\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x1c\n\x0fNPCPropertyType\x18\x03 \x01(\rH\x02\x88\x01\x01\x12\x12\n\x05Notes\x18\x04 \x01(\tH\x03\x88\x01\x01\x42\x10\n\x0e_NPCPropertyIDB\x0e\n\x0c_NPCPropertyB\x12\n\x10_NPCPropertyTypeB\x08\n\x06_Notes\"\x98\x01\n\x10PropertyCfgSheet\x12;\n\x08item_dic\x18\x01 \x03(\x0b\x32).DataConfig.PropertyCfgSheet.ItemDicEntry\x1aG\n\x0cItemDicEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.DataConfig.PropertyCfg:\x02\x38\x01\x62\x06proto3'
)




_PROPERTYCFG = _descriptor.Descriptor(
  name='PropertyCfg',
  full_name='DataConfig.PropertyCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='NPCPropertyID', full_name='DataConfig.PropertyCfg.NPCPropertyID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='NPCProperty', full_name='DataConfig.PropertyCfg.NPCProperty', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='NPCPropertyType', full_name='DataConfig.PropertyCfg.NPCPropertyType', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Notes', full_name='DataConfig.PropertyCfg.Notes', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_NPCPropertyID', full_name='DataConfig.PropertyCfg._NPCPropertyID',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_NPCProperty', full_name='DataConfig.PropertyCfg._NPCProperty',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_NPCPropertyType', full_name='DataConfig.PropertyCfg._NPCPropertyType',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_Notes', full_name='DataConfig.PropertyCfg._Notes',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=31,
  serialized_end=212,
)


_PROPERTYCFGSHEET_ITEMDICENTRY = _descriptor.Descriptor(
  name='ItemDicEntry',
  full_name='DataConfig.PropertyCfgSheet.ItemDicEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DataConfig.PropertyCfgSheet.ItemDicEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='DataConfig.PropertyCfgSheet.ItemDicEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=296,
  serialized_end=367,
)

_PROPERTYCFGSHEET = _descriptor.Descriptor(
  name='PropertyCfgSheet',
  full_name='DataConfig.PropertyCfgSheet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_dic', full_name='DataConfig.PropertyCfgSheet.item_dic', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PROPERTYCFGSHEET_ITEMDICENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=367,
)

_PROPERTYCFG.oneofs_by_name['_NPCPropertyID'].fields.append(
  _PROPERTYCFG.fields_by_name['NPCPropertyID'])
_PROPERTYCFG.fields_by_name['NPCPropertyID'].containing_oneof = _PROPERTYCFG.oneofs_by_name['_NPCPropertyID']
_PROPERTYCFG.oneofs_by_name['_NPCProperty'].fields.append(
  _PROPERTYCFG.fields_by_name['NPCProperty'])
_PROPERTYCFG.fields_by_name['NPCProperty'].containing_oneof = _PROPERTYCFG.oneofs_by_name['_NPCProperty']
_PROPERTYCFG.oneofs_by_name['_NPCPropertyType'].fields.append(
  _PROPERTYCFG.fields_by_name['NPCPropertyType'])
_PROPERTYCFG.fields_by_name['NPCPropertyType'].containing_oneof = _PROPERTYCFG.oneofs_by_name['_NPCPropertyType']
_PROPERTYCFG.oneofs_by_name['_Notes'].fields.append(
  _PROPERTYCFG.fields_by_name['Notes'])
_PROPERTYCFG.fields_by_name['Notes'].containing_oneof = _PROPERTYCFG.oneofs_by_name['_Notes']
_PROPERTYCFGSHEET_ITEMDICENTRY.fields_by_name['value'].message_type = _PROPERTYCFG
_PROPERTYCFGSHEET_ITEMDICENTRY.containing_type = _PROPERTYCFGSHEET
_PROPERTYCFGSHEET.fields_by_name['item_dic'].message_type = _PROPERTYCFGSHEET_ITEMDICENTRY
DESCRIPTOR.message_types_by_name['PropertyCfg'] = _PROPERTYCFG
DESCRIPTOR.message_types_by_name['PropertyCfgSheet'] = _PROPERTYCFGSHEET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PropertyCfg = _reflection.GeneratedProtocolMessageType('PropertyCfg', (_message.Message,), {
  'DESCRIPTOR' : _PROPERTYCFG,
  '__module__' : 'property_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.PropertyCfg)
  })
_sym_db.RegisterMessage(PropertyCfg)

PropertyCfgSheet = _reflection.GeneratedProtocolMessageType('PropertyCfgSheet', (_message.Message,), {

  'ItemDicEntry' : _reflection.GeneratedProtocolMessageType('ItemDicEntry', (_message.Message,), {
    'DESCRIPTOR' : _PROPERTYCFGSHEET_ITEMDICENTRY,
    '__module__' : 'property_pb2'
    # @@protoc_insertion_point(class_scope:DataConfig.PropertyCfgSheet.ItemDicEntry)
    })
  ,
  'DESCRIPTOR' : _PROPERTYCFGSHEET,
  '__module__' : 'property_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.PropertyCfgSheet)
  })
_sym_db.RegisterMessage(PropertyCfgSheet)
_sym_db.RegisterMessage(PropertyCfgSheet.ItemDicEntry)


_PROPERTYCFGSHEET_ITEMDICENTRY._options = None
# @@protoc_insertion_point(module_scope)
