# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prop.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='prop.proto',
  package='DataConfig',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nprop.proto\x12\nDataConfig\"\x8e\x05\n\x07PropCfg\x12\x13\n\x06\x63\x66g_id\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x11\n\x04name\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x16\n\tprop_type\x18\x03 \x01(\rH\x02\x88\x01\x01\x12\x13\n\x06to_bag\x18\x04 \x01(\x08H\x03\x88\x01\x01\x12\x16\n\tmax_count\x18\x05 \x01(\rH\x04\x88\x01\x01\x12\x11\n\x04\x64\x65sc\x18\x06 \x01(\tH\x05\x88\x01\x01\x12\x18\n\x0bicon_M_path\x18\x07 \x01(\tH\x06\x88\x01\x01\x12\x19\n\x0cicon_XL_path\x18\x08 \x01(\tH\x07\x88\x01\x01\x12\x15\n\x08model_id\x18\t \x01(\rH\x08\x88\x01\x01\x12\x15\n\x08skill_id\x18\n \x01(\rH\t\x88\x01\x01\x12\r\n\x05\x62uffs\x18\x0b \x03(\r\x12\x16\n\tcost_prop\x18\x0c \x01(\x05H\n\x88\x01\x01\x12\x17\n\ninit_price\x18\r \x01(\x05H\x0b\x88\x01\x01\x12\x16\n\tadd_price\x18\x0e \x01(\x05H\x0c\x88\x01\x01\x12\x18\n\x0bunlock_type\x18\x0f \x01(\x05H\r\x88\x01\x01\x12\x19\n\x0cunlock_level\x18\x10 \x01(\x05H\x0e\x88\x01\x01\x12\x16\n\tgain_type\x18\x11 \x01(\x05H\x0f\x88\x01\x01\x12\x15\n\x08use_time\x18\x12 \x01(\x02H\x10\x88\x01\x01\x42\t\n\x07_cfg_idB\x07\n\x05_nameB\x0c\n\n_prop_typeB\t\n\x07_to_bagB\x0c\n\n_max_countB\x07\n\x05_descB\x0e\n\x0c_icon_M_pathB\x0f\n\r_icon_XL_pathB\x0b\n\t_model_idB\x0b\n\t_skill_idB\x0c\n\n_cost_propB\r\n\x0b_init_priceB\x0c\n\n_add_priceB\x0e\n\x0c_unlock_typeB\x0f\n\r_unlock_levelB\x0c\n\n_gain_typeB\x0b\n\t_use_time\"\x8c\x01\n\x0cPropCfgSheet\x12\x37\n\x08item_dic\x18\x01 \x03(\x0b\x32%.DataConfig.PropCfgSheet.ItemDicEntry\x1a\x43\n\x0cItemDicEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.DataConfig.PropCfg:\x02\x38\x01\x62\x06proto3'
)




_PROPCFG = _descriptor.Descriptor(
  name='PropCfg',
  full_name='DataConfig.PropCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cfg_id', full_name='DataConfig.PropCfg.cfg_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='DataConfig.PropCfg.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prop_type', full_name='DataConfig.PropCfg.prop_type', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='to_bag', full_name='DataConfig.PropCfg.to_bag', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_count', full_name='DataConfig.PropCfg.max_count', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='desc', full_name='DataConfig.PropCfg.desc', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='icon_M_path', full_name='DataConfig.PropCfg.icon_M_path', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='icon_XL_path', full_name='DataConfig.PropCfg.icon_XL_path', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_id', full_name='DataConfig.PropCfg.model_id', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='skill_id', full_name='DataConfig.PropCfg.skill_id', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='buffs', full_name='DataConfig.PropCfg.buffs', index=10,
      number=11, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cost_prop', full_name='DataConfig.PropCfg.cost_prop', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='init_price', full_name='DataConfig.PropCfg.init_price', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='add_price', full_name='DataConfig.PropCfg.add_price', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unlock_type', full_name='DataConfig.PropCfg.unlock_type', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unlock_level', full_name='DataConfig.PropCfg.unlock_level', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gain_type', full_name='DataConfig.PropCfg.gain_type', index=16,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='use_time', full_name='DataConfig.PropCfg.use_time', index=17,
      number=18, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_cfg_id', full_name='DataConfig.PropCfg._cfg_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_name', full_name='DataConfig.PropCfg._name',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_prop_type', full_name='DataConfig.PropCfg._prop_type',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_to_bag', full_name='DataConfig.PropCfg._to_bag',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_max_count', full_name='DataConfig.PropCfg._max_count',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_desc', full_name='DataConfig.PropCfg._desc',
      index=5, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_icon_M_path', full_name='DataConfig.PropCfg._icon_M_path',
      index=6, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_icon_XL_path', full_name='DataConfig.PropCfg._icon_XL_path',
      index=7, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_model_id', full_name='DataConfig.PropCfg._model_id',
      index=8, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_skill_id', full_name='DataConfig.PropCfg._skill_id',
      index=9, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_cost_prop', full_name='DataConfig.PropCfg._cost_prop',
      index=10, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_init_price', full_name='DataConfig.PropCfg._init_price',
      index=11, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_add_price', full_name='DataConfig.PropCfg._add_price',
      index=12, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_unlock_type', full_name='DataConfig.PropCfg._unlock_type',
      index=13, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_unlock_level', full_name='DataConfig.PropCfg._unlock_level',
      index=14, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_gain_type', full_name='DataConfig.PropCfg._gain_type',
      index=15, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_use_time', full_name='DataConfig.PropCfg._use_time',
      index=16, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=27,
  serialized_end=681,
)


_PROPCFGSHEET_ITEMDICENTRY = _descriptor.Descriptor(
  name='ItemDicEntry',
  full_name='DataConfig.PropCfgSheet.ItemDicEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DataConfig.PropCfgSheet.ItemDicEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='DataConfig.PropCfgSheet.ItemDicEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=757,
  serialized_end=824,
)

_PROPCFGSHEET = _descriptor.Descriptor(
  name='PropCfgSheet',
  full_name='DataConfig.PropCfgSheet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_dic', full_name='DataConfig.PropCfgSheet.item_dic', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PROPCFGSHEET_ITEMDICENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=684,
  serialized_end=824,
)

_PROPCFG.oneofs_by_name['_cfg_id'].fields.append(
  _PROPCFG.fields_by_name['cfg_id'])
_PROPCFG.fields_by_name['cfg_id'].containing_oneof = _PROPCFG.oneofs_by_name['_cfg_id']
_PROPCFG.oneofs_by_name['_name'].fields.append(
  _PROPCFG.fields_by_name['name'])
_PROPCFG.fields_by_name['name'].containing_oneof = _PROPCFG.oneofs_by_name['_name']
_PROPCFG.oneofs_by_name['_prop_type'].fields.append(
  _PROPCFG.fields_by_name['prop_type'])
_PROPCFG.fields_by_name['prop_type'].containing_oneof = _PROPCFG.oneofs_by_name['_prop_type']
_PROPCFG.oneofs_by_name['_to_bag'].fields.append(
  _PROPCFG.fields_by_name['to_bag'])
_PROPCFG.fields_by_name['to_bag'].containing_oneof = _PROPCFG.oneofs_by_name['_to_bag']
_PROPCFG.oneofs_by_name['_max_count'].fields.append(
  _PROPCFG.fields_by_name['max_count'])
_PROPCFG.fields_by_name['max_count'].containing_oneof = _PROPCFG.oneofs_by_name['_max_count']
_PROPCFG.oneofs_by_name['_desc'].fields.append(
  _PROPCFG.fields_by_name['desc'])
_PROPCFG.fields_by_name['desc'].containing_oneof = _PROPCFG.oneofs_by_name['_desc']
_PROPCFG.oneofs_by_name['_icon_M_path'].fields.append(
  _PROPCFG.fields_by_name['icon_M_path'])
_PROPCFG.fields_by_name['icon_M_path'].containing_oneof = _PROPCFG.oneofs_by_name['_icon_M_path']
_PROPCFG.oneofs_by_name['_icon_XL_path'].fields.append(
  _PROPCFG.fields_by_name['icon_XL_path'])
_PROPCFG.fields_by_name['icon_XL_path'].containing_oneof = _PROPCFG.oneofs_by_name['_icon_XL_path']
_PROPCFG.oneofs_by_name['_model_id'].fields.append(
  _PROPCFG.fields_by_name['model_id'])
_PROPCFG.fields_by_name['model_id'].containing_oneof = _PROPCFG.oneofs_by_name['_model_id']
_PROPCFG.oneofs_by_name['_skill_id'].fields.append(
  _PROPCFG.fields_by_name['skill_id'])
_PROPCFG.fields_by_name['skill_id'].containing_oneof = _PROPCFG.oneofs_by_name['_skill_id']
_PROPCFG.oneofs_by_name['_cost_prop'].fields.append(
  _PROPCFG.fields_by_name['cost_prop'])
_PROPCFG.fields_by_name['cost_prop'].containing_oneof = _PROPCFG.oneofs_by_name['_cost_prop']
_PROPCFG.oneofs_by_name['_init_price'].fields.append(
  _PROPCFG.fields_by_name['init_price'])
_PROPCFG.fields_by_name['init_price'].containing_oneof = _PROPCFG.oneofs_by_name['_init_price']
_PROPCFG.oneofs_by_name['_add_price'].fields.append(
  _PROPCFG.fields_by_name['add_price'])
_PROPCFG.fields_by_name['add_price'].containing_oneof = _PROPCFG.oneofs_by_name['_add_price']
_PROPCFG.oneofs_by_name['_unlock_type'].fields.append(
  _PROPCFG.fields_by_name['unlock_type'])
_PROPCFG.fields_by_name['unlock_type'].containing_oneof = _PROPCFG.oneofs_by_name['_unlock_type']
_PROPCFG.oneofs_by_name['_unlock_level'].fields.append(
  _PROPCFG.fields_by_name['unlock_level'])
_PROPCFG.fields_by_name['unlock_level'].containing_oneof = _PROPCFG.oneofs_by_name['_unlock_level']
_PROPCFG.oneofs_by_name['_gain_type'].fields.append(
  _PROPCFG.fields_by_name['gain_type'])
_PROPCFG.fields_by_name['gain_type'].containing_oneof = _PROPCFG.oneofs_by_name['_gain_type']
_PROPCFG.oneofs_by_name['_use_time'].fields.append(
  _PROPCFG.fields_by_name['use_time'])
_PROPCFG.fields_by_name['use_time'].containing_oneof = _PROPCFG.oneofs_by_name['_use_time']
_PROPCFGSHEET_ITEMDICENTRY.fields_by_name['value'].message_type = _PROPCFG
_PROPCFGSHEET_ITEMDICENTRY.containing_type = _PROPCFGSHEET
_PROPCFGSHEET.fields_by_name['item_dic'].message_type = _PROPCFGSHEET_ITEMDICENTRY
DESCRIPTOR.message_types_by_name['PropCfg'] = _PROPCFG
DESCRIPTOR.message_types_by_name['PropCfgSheet'] = _PROPCFGSHEET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PropCfg = _reflection.GeneratedProtocolMessageType('PropCfg', (_message.Message,), {
  'DESCRIPTOR' : _PROPCFG,
  '__module__' : 'prop_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.PropCfg)
  })
_sym_db.RegisterMessage(PropCfg)

PropCfgSheet = _reflection.GeneratedProtocolMessageType('PropCfgSheet', (_message.Message,), {

  'ItemDicEntry' : _reflection.GeneratedProtocolMessageType('ItemDicEntry', (_message.Message,), {
    'DESCRIPTOR' : _PROPCFGSHEET_ITEMDICENTRY,
    '__module__' : 'prop_pb2'
    # @@protoc_insertion_point(class_scope:DataConfig.PropCfgSheet.ItemDicEntry)
    })
  ,
  'DESCRIPTOR' : _PROPCFGSHEET,
  '__module__' : 'prop_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.PropCfgSheet)
  })
_sym_db.RegisterMessage(PropCfgSheet)
_sym_db.RegisterMessage(PropCfgSheet.ItemDicEntry)


_PROPCFGSHEET_ITEMDICENTRY._options = None
# @@protoc_insertion_point(module_scope)
