# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: skillinputtagcompare.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='skillinputtagcompare.proto',
  package='DataConfig',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1askillinputtagcompare.proto\x12\nDataConfig\"\xb9\x01\n\x17SkillInputTagCompareCfg\x12\x13\n\x06\x63\x66g_id\x18\x01 \x01(\rH\x00\x88\x01\x01\x12K\n\x08tag_list\x18\x02 \x03(\x0b\x32\x39.DataConfig.SkillInputTagCompareCfg.InternalType_tag_list\x1a\x31\n\x15InternalType_tag_list\x12\x10\n\x03tag\x18\x01 \x01(\rH\x00\x88\x01\x01\x42\x06\n\x04_tagB\t\n\x07_cfg_id\"\xbc\x01\n\x1cSkillInputTagCompareCfgSheet\x12G\n\x08item_dic\x18\x01 \x03(\x0b\x32\x35.DataConfig.SkillInputTagCompareCfgSheet.ItemDicEntry\x1aS\n\x0cItemDicEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x32\n\x05value\x18\x02 \x01(\x0b\x32#.DataConfig.SkillInputTagCompareCfg:\x02\x38\x01\x62\x06proto3'
)




_SKILLINPUTTAGCOMPARECFG_INTERNALTYPE_TAG_LIST = _descriptor.Descriptor(
  name='InternalType_tag_list',
  full_name='DataConfig.SkillInputTagCompareCfg.InternalType_tag_list',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag', full_name='DataConfig.SkillInputTagCompareCfg.InternalType_tag_list.tag', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_tag', full_name='DataConfig.SkillInputTagCompareCfg.InternalType_tag_list._tag',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=168,
  serialized_end=217,
)

_SKILLINPUTTAGCOMPARECFG = _descriptor.Descriptor(
  name='SkillInputTagCompareCfg',
  full_name='DataConfig.SkillInputTagCompareCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cfg_id', full_name='DataConfig.SkillInputTagCompareCfg.cfg_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tag_list', full_name='DataConfig.SkillInputTagCompareCfg.tag_list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SKILLINPUTTAGCOMPARECFG_INTERNALTYPE_TAG_LIST, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_cfg_id', full_name='DataConfig.SkillInputTagCompareCfg._cfg_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=43,
  serialized_end=228,
)


_SKILLINPUTTAGCOMPARECFGSHEET_ITEMDICENTRY = _descriptor.Descriptor(
  name='ItemDicEntry',
  full_name='DataConfig.SkillInputTagCompareCfgSheet.ItemDicEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DataConfig.SkillInputTagCompareCfgSheet.ItemDicEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='DataConfig.SkillInputTagCompareCfgSheet.ItemDicEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=336,
  serialized_end=419,
)

_SKILLINPUTTAGCOMPARECFGSHEET = _descriptor.Descriptor(
  name='SkillInputTagCompareCfgSheet',
  full_name='DataConfig.SkillInputTagCompareCfgSheet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_dic', full_name='DataConfig.SkillInputTagCompareCfgSheet.item_dic', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SKILLINPUTTAGCOMPARECFGSHEET_ITEMDICENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=419,
)

_SKILLINPUTTAGCOMPARECFG_INTERNALTYPE_TAG_LIST.containing_type = _SKILLINPUTTAGCOMPARECFG
_SKILLINPUTTAGCOMPARECFG_INTERNALTYPE_TAG_LIST.oneofs_by_name['_tag'].fields.append(
  _SKILLINPUTTAGCOMPARECFG_INTERNALTYPE_TAG_LIST.fields_by_name['tag'])
_SKILLINPUTTAGCOMPARECFG_INTERNALTYPE_TAG_LIST.fields_by_name['tag'].containing_oneof = _SKILLINPUTTAGCOMPARECFG_INTERNALTYPE_TAG_LIST.oneofs_by_name['_tag']
_SKILLINPUTTAGCOMPARECFG.fields_by_name['tag_list'].message_type = _SKILLINPUTTAGCOMPARECFG_INTERNALTYPE_TAG_LIST
_SKILLINPUTTAGCOMPARECFG.oneofs_by_name['_cfg_id'].fields.append(
  _SKILLINPUTTAGCOMPARECFG.fields_by_name['cfg_id'])
_SKILLINPUTTAGCOMPARECFG.fields_by_name['cfg_id'].containing_oneof = _SKILLINPUTTAGCOMPARECFG.oneofs_by_name['_cfg_id']
_SKILLINPUTTAGCOMPARECFGSHEET_ITEMDICENTRY.fields_by_name['value'].message_type = _SKILLINPUTTAGCOMPARECFG
_SKILLINPUTTAGCOMPARECFGSHEET_ITEMDICENTRY.containing_type = _SKILLINPUTTAGCOMPARECFGSHEET
_SKILLINPUTTAGCOMPARECFGSHEET.fields_by_name['item_dic'].message_type = _SKILLINPUTTAGCOMPARECFGSHEET_ITEMDICENTRY
DESCRIPTOR.message_types_by_name['SkillInputTagCompareCfg'] = _SKILLINPUTTAGCOMPARECFG
DESCRIPTOR.message_types_by_name['SkillInputTagCompareCfgSheet'] = _SKILLINPUTTAGCOMPARECFGSHEET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SkillInputTagCompareCfg = _reflection.GeneratedProtocolMessageType('SkillInputTagCompareCfg', (_message.Message,), {

  'InternalType_tag_list' : _reflection.GeneratedProtocolMessageType('InternalType_tag_list', (_message.Message,), {
    'DESCRIPTOR' : _SKILLINPUTTAGCOMPARECFG_INTERNALTYPE_TAG_LIST,
    '__module__' : 'skillinputtagcompare_pb2'
    # @@protoc_insertion_point(class_scope:DataConfig.SkillInputTagCompareCfg.InternalType_tag_list)
    })
  ,
  'DESCRIPTOR' : _SKILLINPUTTAGCOMPARECFG,
  '__module__' : 'skillinputtagcompare_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.SkillInputTagCompareCfg)
  })
_sym_db.RegisterMessage(SkillInputTagCompareCfg)
_sym_db.RegisterMessage(SkillInputTagCompareCfg.InternalType_tag_list)

SkillInputTagCompareCfgSheet = _reflection.GeneratedProtocolMessageType('SkillInputTagCompareCfgSheet', (_message.Message,), {

  'ItemDicEntry' : _reflection.GeneratedProtocolMessageType('ItemDicEntry', (_message.Message,), {
    'DESCRIPTOR' : _SKILLINPUTTAGCOMPARECFGSHEET_ITEMDICENTRY,
    '__module__' : 'skillinputtagcompare_pb2'
    # @@protoc_insertion_point(class_scope:DataConfig.SkillInputTagCompareCfgSheet.ItemDicEntry)
    })
  ,
  'DESCRIPTOR' : _SKILLINPUTTAGCOMPARECFGSHEET,
  '__module__' : 'skillinputtagcompare_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.SkillInputTagCompareCfgSheet)
  })
_sym_db.RegisterMessage(SkillInputTagCompareCfgSheet)
_sym_db.RegisterMessage(SkillInputTagCompareCfgSheet.ItemDicEntry)


_SKILLINPUTTAGCOMPARECFGSHEET_ITEMDICENTRY._options = None
# @@protoc_insertion_point(module_scope)
