# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: structtest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='structtest.proto',
  package='DataConfig',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10structtest.proto\x12\nDataConfig\"\x97\x04\n\rStructTestCfg\x12\x13\n\x06\x63\x66g_id\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x16\n\tstartAttr\x18\x02 \x01(\rH\x01\x88\x01\x01\x12G\n\x0bstruct1list\x18\x03 \x03(\x0b\x32\x32.DataConfig.StructTestCfg.InternalType_struct1list\x12\x14\n\x07midAttr\x18\x04 \x01(\rH\x02\x88\x01\x01\x12G\n\x0bstruct2list\x18\x05 \x03(\x0b\x32\x32.DataConfig.StructTestCfg.InternalType_struct2list\x12\x14\n\x07\x65ndAttr\x18\x06 \x01(\rH\x03\x88\x01\x01\x1at\n\x18InternalType_struct1list\x12\x12\n\x05\x61ttr1\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x12\n\x05\x61ttr2\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x12\n\x05\x61ttr3\x18\x03 \x01(\rH\x02\x88\x01\x01\x42\x08\n\x06_attr1B\x08\n\x06_attr2B\x08\n\x06_attr3\x1at\n\x18InternalType_struct2list\x12\x12\n\x05\x61ttr1\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x12\n\x05\x61ttr2\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x12\n\x05\x61ttr3\x18\x03 \x01(\rH\x02\x88\x01\x01\x42\x08\n\x06_attr1B\x08\n\x06_attr2B\x08\n\x06_attr3B\t\n\x07_cfg_idB\x0c\n\n_startAttrB\n\n\x08_midAttrB\n\n\x08_endAttr\"\x9e\x01\n\x12StructTestCfgSheet\x12=\n\x08item_dic\x18\x01 \x03(\x0b\x32+.DataConfig.StructTestCfgSheet.ItemDicEntry\x1aI\n\x0cItemDicEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.DataConfig.StructTestCfg:\x02\x38\x01\x62\x06proto3'
)




_STRUCTTESTCFG_INTERNALTYPE_STRUCT1LIST = _descriptor.Descriptor(
  name='InternalType_struct1list',
  full_name='DataConfig.StructTestCfg.InternalType_struct1list',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='attr1', full_name='DataConfig.StructTestCfg.InternalType_struct1list.attr1', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attr2', full_name='DataConfig.StructTestCfg.InternalType_struct1list.attr2', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attr3', full_name='DataConfig.StructTestCfg.InternalType_struct1list.attr3', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_attr1', full_name='DataConfig.StructTestCfg.InternalType_struct1list._attr1',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_attr2', full_name='DataConfig.StructTestCfg.InternalType_struct1list._attr2',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_attr3', full_name='DataConfig.StructTestCfg.InternalType_struct1list._attr3',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=285,
  serialized_end=401,
)

_STRUCTTESTCFG_INTERNALTYPE_STRUCT2LIST = _descriptor.Descriptor(
  name='InternalType_struct2list',
  full_name='DataConfig.StructTestCfg.InternalType_struct2list',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='attr1', full_name='DataConfig.StructTestCfg.InternalType_struct2list.attr1', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attr2', full_name='DataConfig.StructTestCfg.InternalType_struct2list.attr2', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attr3', full_name='DataConfig.StructTestCfg.InternalType_struct2list.attr3', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_attr1', full_name='DataConfig.StructTestCfg.InternalType_struct2list._attr1',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_attr2', full_name='DataConfig.StructTestCfg.InternalType_struct2list._attr2',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_attr3', full_name='DataConfig.StructTestCfg.InternalType_struct2list._attr3',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=403,
  serialized_end=519,
)

_STRUCTTESTCFG = _descriptor.Descriptor(
  name='StructTestCfg',
  full_name='DataConfig.StructTestCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cfg_id', full_name='DataConfig.StructTestCfg.cfg_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='startAttr', full_name='DataConfig.StructTestCfg.startAttr', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='struct1list', full_name='DataConfig.StructTestCfg.struct1list', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='midAttr', full_name='DataConfig.StructTestCfg.midAttr', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='struct2list', full_name='DataConfig.StructTestCfg.struct2list', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='endAttr', full_name='DataConfig.StructTestCfg.endAttr', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_STRUCTTESTCFG_INTERNALTYPE_STRUCT1LIST, _STRUCTTESTCFG_INTERNALTYPE_STRUCT2LIST, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_cfg_id', full_name='DataConfig.StructTestCfg._cfg_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_startAttr', full_name='DataConfig.StructTestCfg._startAttr',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_midAttr', full_name='DataConfig.StructTestCfg._midAttr',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_endAttr', full_name='DataConfig.StructTestCfg._endAttr',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=33,
  serialized_end=568,
)


_STRUCTTESTCFGSHEET_ITEMDICENTRY = _descriptor.Descriptor(
  name='ItemDicEntry',
  full_name='DataConfig.StructTestCfgSheet.ItemDicEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DataConfig.StructTestCfgSheet.ItemDicEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='DataConfig.StructTestCfgSheet.ItemDicEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=656,
  serialized_end=729,
)

_STRUCTTESTCFGSHEET = _descriptor.Descriptor(
  name='StructTestCfgSheet',
  full_name='DataConfig.StructTestCfgSheet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_dic', full_name='DataConfig.StructTestCfgSheet.item_dic', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_STRUCTTESTCFGSHEET_ITEMDICENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=571,
  serialized_end=729,
)

_STRUCTTESTCFG_INTERNALTYPE_STRUCT1LIST.containing_type = _STRUCTTESTCFG
_STRUCTTESTCFG_INTERNALTYPE_STRUCT1LIST.oneofs_by_name['_attr1'].fields.append(
  _STRUCTTESTCFG_INTERNALTYPE_STRUCT1LIST.fields_by_name['attr1'])
_STRUCTTESTCFG_INTERNALTYPE_STRUCT1LIST.fields_by_name['attr1'].containing_oneof = _STRUCTTESTCFG_INTERNALTYPE_STRUCT1LIST.oneofs_by_name['_attr1']
_STRUCTTESTCFG_INTERNALTYPE_STRUCT1LIST.oneofs_by_name['_attr2'].fields.append(
  _STRUCTTESTCFG_INTERNALTYPE_STRUCT1LIST.fields_by_name['attr2'])
_STRUCTTESTCFG_INTERNALTYPE_STRUCT1LIST.fields_by_name['attr2'].containing_oneof = _STRUCTTESTCFG_INTERNALTYPE_STRUCT1LIST.oneofs_by_name['_attr2']
_STRUCTTESTCFG_INTERNALTYPE_STRUCT1LIST.oneofs_by_name['_attr3'].fields.append(
  _STRUCTTESTCFG_INTERNALTYPE_STRUCT1LIST.fields_by_name['attr3'])
_STRUCTTESTCFG_INTERNALTYPE_STRUCT1LIST.fields_by_name['attr3'].containing_oneof = _STRUCTTESTCFG_INTERNALTYPE_STRUCT1LIST.oneofs_by_name['_attr3']
_STRUCTTESTCFG_INTERNALTYPE_STRUCT2LIST.containing_type = _STRUCTTESTCFG
_STRUCTTESTCFG_INTERNALTYPE_STRUCT2LIST.oneofs_by_name['_attr1'].fields.append(
  _STRUCTTESTCFG_INTERNALTYPE_STRUCT2LIST.fields_by_name['attr1'])
_STRUCTTESTCFG_INTERNALTYPE_STRUCT2LIST.fields_by_name['attr1'].containing_oneof = _STRUCTTESTCFG_INTERNALTYPE_STRUCT2LIST.oneofs_by_name['_attr1']
_STRUCTTESTCFG_INTERNALTYPE_STRUCT2LIST.oneofs_by_name['_attr2'].fields.append(
  _STRUCTTESTCFG_INTERNALTYPE_STRUCT2LIST.fields_by_name['attr2'])
_STRUCTTESTCFG_INTERNALTYPE_STRUCT2LIST.fields_by_name['attr2'].containing_oneof = _STRUCTTESTCFG_INTERNALTYPE_STRUCT2LIST.oneofs_by_name['_attr2']
_STRUCTTESTCFG_INTERNALTYPE_STRUCT2LIST.oneofs_by_name['_attr3'].fields.append(
  _STRUCTTESTCFG_INTERNALTYPE_STRUCT2LIST.fields_by_name['attr3'])
_STRUCTTESTCFG_INTERNALTYPE_STRUCT2LIST.fields_by_name['attr3'].containing_oneof = _STRUCTTESTCFG_INTERNALTYPE_STRUCT2LIST.oneofs_by_name['_attr3']
_STRUCTTESTCFG.fields_by_name['struct1list'].message_type = _STRUCTTESTCFG_INTERNALTYPE_STRUCT1LIST
_STRUCTTESTCFG.fields_by_name['struct2list'].message_type = _STRUCTTESTCFG_INTERNALTYPE_STRUCT2LIST
_STRUCTTESTCFG.oneofs_by_name['_cfg_id'].fields.append(
  _STRUCTTESTCFG.fields_by_name['cfg_id'])
_STRUCTTESTCFG.fields_by_name['cfg_id'].containing_oneof = _STRUCTTESTCFG.oneofs_by_name['_cfg_id']
_STRUCTTESTCFG.oneofs_by_name['_startAttr'].fields.append(
  _STRUCTTESTCFG.fields_by_name['startAttr'])
_STRUCTTESTCFG.fields_by_name['startAttr'].containing_oneof = _STRUCTTESTCFG.oneofs_by_name['_startAttr']
_STRUCTTESTCFG.oneofs_by_name['_midAttr'].fields.append(
  _STRUCTTESTCFG.fields_by_name['midAttr'])
_STRUCTTESTCFG.fields_by_name['midAttr'].containing_oneof = _STRUCTTESTCFG.oneofs_by_name['_midAttr']
_STRUCTTESTCFG.oneofs_by_name['_endAttr'].fields.append(
  _STRUCTTESTCFG.fields_by_name['endAttr'])
_STRUCTTESTCFG.fields_by_name['endAttr'].containing_oneof = _STRUCTTESTCFG.oneofs_by_name['_endAttr']
_STRUCTTESTCFGSHEET_ITEMDICENTRY.fields_by_name['value'].message_type = _STRUCTTESTCFG
_STRUCTTESTCFGSHEET_ITEMDICENTRY.containing_type = _STRUCTTESTCFGSHEET
_STRUCTTESTCFGSHEET.fields_by_name['item_dic'].message_type = _STRUCTTESTCFGSHEET_ITEMDICENTRY
DESCRIPTOR.message_types_by_name['StructTestCfg'] = _STRUCTTESTCFG
DESCRIPTOR.message_types_by_name['StructTestCfgSheet'] = _STRUCTTESTCFGSHEET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StructTestCfg = _reflection.GeneratedProtocolMessageType('StructTestCfg', (_message.Message,), {

  'InternalType_struct1list' : _reflection.GeneratedProtocolMessageType('InternalType_struct1list', (_message.Message,), {
    'DESCRIPTOR' : _STRUCTTESTCFG_INTERNALTYPE_STRUCT1LIST,
    '__module__' : 'structtest_pb2'
    # @@protoc_insertion_point(class_scope:DataConfig.StructTestCfg.InternalType_struct1list)
    })
  ,

  'InternalType_struct2list' : _reflection.GeneratedProtocolMessageType('InternalType_struct2list', (_message.Message,), {
    'DESCRIPTOR' : _STRUCTTESTCFG_INTERNALTYPE_STRUCT2LIST,
    '__module__' : 'structtest_pb2'
    # @@protoc_insertion_point(class_scope:DataConfig.StructTestCfg.InternalType_struct2list)
    })
  ,
  'DESCRIPTOR' : _STRUCTTESTCFG,
  '__module__' : 'structtest_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.StructTestCfg)
  })
_sym_db.RegisterMessage(StructTestCfg)
_sym_db.RegisterMessage(StructTestCfg.InternalType_struct1list)
_sym_db.RegisterMessage(StructTestCfg.InternalType_struct2list)

StructTestCfgSheet = _reflection.GeneratedProtocolMessageType('StructTestCfgSheet', (_message.Message,), {

  'ItemDicEntry' : _reflection.GeneratedProtocolMessageType('ItemDicEntry', (_message.Message,), {
    'DESCRIPTOR' : _STRUCTTESTCFGSHEET_ITEMDICENTRY,
    '__module__' : 'structtest_pb2'
    # @@protoc_insertion_point(class_scope:DataConfig.StructTestCfgSheet.ItemDicEntry)
    })
  ,
  'DESCRIPTOR' : _STRUCTTESTCFGSHEET,
  '__module__' : 'structtest_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.StructTestCfgSheet)
  })
_sym_db.RegisterMessage(StructTestCfgSheet)
_sym_db.RegisterMessage(StructTestCfgSheet.ItemDicEntry)


_STRUCTTESTCFGSHEET_ITEMDICENTRY._options = None
# @@protoc_insertion_point(module_scope)
