# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tag.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tag.proto',
  package='DataConfig',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ttag.proto\x12\nDataConfig\"D\n\x06TagCfg\x12\x13\n\x06\x63\x66g_id\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x11\n\x04name\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\t\n\x07_cfg_idB\x07\n\x05_name\"\x89\x01\n\x0bTagCfgSheet\x12\x36\n\x08item_dic\x18\x01 \x03(\x0b\x32$.DataConfig.TagCfgSheet.ItemDicEntry\x1a\x42\n\x0cItemDicEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.DataConfig.TagCfg:\x02\x38\x01\x62\x06proto3'
)




_TAGCFG = _descriptor.Descriptor(
  name='TagCfg',
  full_name='DataConfig.TagCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cfg_id', full_name='DataConfig.TagCfg.cfg_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='DataConfig.TagCfg.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_cfg_id', full_name='DataConfig.TagCfg._cfg_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_name', full_name='DataConfig.TagCfg._name',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=25,
  serialized_end=93,
)


_TAGCFGSHEET_ITEMDICENTRY = _descriptor.Descriptor(
  name='ItemDicEntry',
  full_name='DataConfig.TagCfgSheet.ItemDicEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DataConfig.TagCfgSheet.ItemDicEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='DataConfig.TagCfgSheet.ItemDicEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=233,
)

_TAGCFGSHEET = _descriptor.Descriptor(
  name='TagCfgSheet',
  full_name='DataConfig.TagCfgSheet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_dic', full_name='DataConfig.TagCfgSheet.item_dic', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_TAGCFGSHEET_ITEMDICENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=233,
)

_TAGCFG.oneofs_by_name['_cfg_id'].fields.append(
  _TAGCFG.fields_by_name['cfg_id'])
_TAGCFG.fields_by_name['cfg_id'].containing_oneof = _TAGCFG.oneofs_by_name['_cfg_id']
_TAGCFG.oneofs_by_name['_name'].fields.append(
  _TAGCFG.fields_by_name['name'])
_TAGCFG.fields_by_name['name'].containing_oneof = _TAGCFG.oneofs_by_name['_name']
_TAGCFGSHEET_ITEMDICENTRY.fields_by_name['value'].message_type = _TAGCFG
_TAGCFGSHEET_ITEMDICENTRY.containing_type = _TAGCFGSHEET
_TAGCFGSHEET.fields_by_name['item_dic'].message_type = _TAGCFGSHEET_ITEMDICENTRY
DESCRIPTOR.message_types_by_name['TagCfg'] = _TAGCFG
DESCRIPTOR.message_types_by_name['TagCfgSheet'] = _TAGCFGSHEET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TagCfg = _reflection.GeneratedProtocolMessageType('TagCfg', (_message.Message,), {
  'DESCRIPTOR' : _TAGCFG,
  '__module__' : 'tag_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.TagCfg)
  })
_sym_db.RegisterMessage(TagCfg)

TagCfgSheet = _reflection.GeneratedProtocolMessageType('TagCfgSheet', (_message.Message,), {

  'ItemDicEntry' : _reflection.GeneratedProtocolMessageType('ItemDicEntry', (_message.Message,), {
    'DESCRIPTOR' : _TAGCFGSHEET_ITEMDICENTRY,
    '__module__' : 'tag_pb2'
    # @@protoc_insertion_point(class_scope:DataConfig.TagCfgSheet.ItemDicEntry)
    })
  ,
  'DESCRIPTOR' : _TAGCFGSHEET,
  '__module__' : 'tag_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.TagCfgSheet)
  })
_sym_db.RegisterMessage(TagCfgSheet)
_sym_db.RegisterMessage(TagCfgSheet.ItemDicEntry)


_TAGCFGSHEET_ITEMDICENTRY._options = None
# @@protoc_insertion_point(module_scope)
