# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weapon.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='weapon.proto',
  package='DataConfig',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cweapon.proto\x12\nDataConfig\"\xc9\x01\n\tWeaponCfg\x12\x13\n\x06\x63\x66g_id\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x15\n\x08skill_id\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x18\n\x0b\x61\x64\x64_buff_id\x18\x03 \x01(\rH\x02\x88\x01\x01\x12\x17\n\nskill_desc\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x17\n\ntargetType\x18\x05 \x01(\x05H\x04\x88\x01\x01\x42\t\n\x07_cfg_idB\x0b\n\t_skill_idB\x0e\n\x0c_add_buff_idB\r\n\x0b_skill_descB\r\n\x0b_targetType\"\x92\x01\n\x0eWeaponCfgSheet\x12\x39\n\x08item_dic\x18\x01 \x03(\x0b\x32\'.DataConfig.WeaponCfgSheet.ItemDicEntry\x1a\x45\n\x0cItemDicEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.DataConfig.WeaponCfg:\x02\x38\x01\x62\x06proto3'
)




_WEAPONCFG = _descriptor.Descriptor(
  name='WeaponCfg',
  full_name='DataConfig.WeaponCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cfg_id', full_name='DataConfig.WeaponCfg.cfg_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='skill_id', full_name='DataConfig.WeaponCfg.skill_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='add_buff_id', full_name='DataConfig.WeaponCfg.add_buff_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='skill_desc', full_name='DataConfig.WeaponCfg.skill_desc', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='targetType', full_name='DataConfig.WeaponCfg.targetType', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_cfg_id', full_name='DataConfig.WeaponCfg._cfg_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_skill_id', full_name='DataConfig.WeaponCfg._skill_id',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_add_buff_id', full_name='DataConfig.WeaponCfg._add_buff_id',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_skill_desc', full_name='DataConfig.WeaponCfg._skill_desc',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_targetType', full_name='DataConfig.WeaponCfg._targetType',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=29,
  serialized_end=230,
)


_WEAPONCFGSHEET_ITEMDICENTRY = _descriptor.Descriptor(
  name='ItemDicEntry',
  full_name='DataConfig.WeaponCfgSheet.ItemDicEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DataConfig.WeaponCfgSheet.ItemDicEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='DataConfig.WeaponCfgSheet.ItemDicEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=310,
  serialized_end=379,
)

_WEAPONCFGSHEET = _descriptor.Descriptor(
  name='WeaponCfgSheet',
  full_name='DataConfig.WeaponCfgSheet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_dic', full_name='DataConfig.WeaponCfgSheet.item_dic', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_WEAPONCFGSHEET_ITEMDICENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=379,
)

_WEAPONCFG.oneofs_by_name['_cfg_id'].fields.append(
  _WEAPONCFG.fields_by_name['cfg_id'])
_WEAPONCFG.fields_by_name['cfg_id'].containing_oneof = _WEAPONCFG.oneofs_by_name['_cfg_id']
_WEAPONCFG.oneofs_by_name['_skill_id'].fields.append(
  _WEAPONCFG.fields_by_name['skill_id'])
_WEAPONCFG.fields_by_name['skill_id'].containing_oneof = _WEAPONCFG.oneofs_by_name['_skill_id']
_WEAPONCFG.oneofs_by_name['_add_buff_id'].fields.append(
  _WEAPONCFG.fields_by_name['add_buff_id'])
_WEAPONCFG.fields_by_name['add_buff_id'].containing_oneof = _WEAPONCFG.oneofs_by_name['_add_buff_id']
_WEAPONCFG.oneofs_by_name['_skill_desc'].fields.append(
  _WEAPONCFG.fields_by_name['skill_desc'])
_WEAPONCFG.fields_by_name['skill_desc'].containing_oneof = _WEAPONCFG.oneofs_by_name['_skill_desc']
_WEAPONCFG.oneofs_by_name['_targetType'].fields.append(
  _WEAPONCFG.fields_by_name['targetType'])
_WEAPONCFG.fields_by_name['targetType'].containing_oneof = _WEAPONCFG.oneofs_by_name['_targetType']
_WEAPONCFGSHEET_ITEMDICENTRY.fields_by_name['value'].message_type = _WEAPONCFG
_WEAPONCFGSHEET_ITEMDICENTRY.containing_type = _WEAPONCFGSHEET
_WEAPONCFGSHEET.fields_by_name['item_dic'].message_type = _WEAPONCFGSHEET_ITEMDICENTRY
DESCRIPTOR.message_types_by_name['WeaponCfg'] = _WEAPONCFG
DESCRIPTOR.message_types_by_name['WeaponCfgSheet'] = _WEAPONCFGSHEET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WeaponCfg = _reflection.GeneratedProtocolMessageType('WeaponCfg', (_message.Message,), {
  'DESCRIPTOR' : _WEAPONCFG,
  '__module__' : 'weapon_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.WeaponCfg)
  })
_sym_db.RegisterMessage(WeaponCfg)

WeaponCfgSheet = _reflection.GeneratedProtocolMessageType('WeaponCfgSheet', (_message.Message,), {

  'ItemDicEntry' : _reflection.GeneratedProtocolMessageType('ItemDicEntry', (_message.Message,), {
    'DESCRIPTOR' : _WEAPONCFGSHEET_ITEMDICENTRY,
    '__module__' : 'weapon_pb2'
    # @@protoc_insertion_point(class_scope:DataConfig.WeaponCfgSheet.ItemDicEntry)
    })
  ,
  'DESCRIPTOR' : _WEAPONCFGSHEET,
  '__module__' : 'weapon_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig.WeaponCfgSheet)
  })
_sym_db.RegisterMessage(WeaponCfgSheet)
_sym_db.RegisterMessage(WeaponCfgSheet.ItemDicEntry)


_WEAPONCFGSHEET_ITEMDICENTRY._options = None
# @@protoc_insertion_point(module_scope)
