// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: pbbsls.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pbbsls {

  /// <summary>Holder for reflection information generated from pbbsls.proto</summary>
  public static partial class PbbslsReflection {

    #region Descriptor
    /// <summary>File descriptor for pbbsls.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PbbslsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxwYmJzbHMucHJvdG8SBnBiYnNscyoTCgdSZXRDb2RlEggKBE5PTkUQAEIK",
            "WgguL3BiYnNsc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Pbbsls.RetCode), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum RetCode {
    [pbr::OriginalName("NONE")] None = 0,
  }

  #endregion

}

#endregion Designer generated code
