// Generated by ProtoGen, Version=2.4.1.555, Culture=neutral, PublicKeyToken=17b3b1f090c3ea48.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace Protocol {
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class ProtoConfig {
  
    #region Extension registration
    public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
    }
    #endregion
    #region Static variables
    #endregion
    #region Descriptor
    public static pbd::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbd::FileDescriptor descriptor;
    
    static ProtoConfig() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJwcm90b19jb25maWcucHJvdG8SCFByb3RvY29sGh1pbmNsdWRlL3lkX2Zp", 
            "ZWxkb3B0aW9ucy5wcm90byo5CgpFbnRpdHlUeXBlEggKBEhlcm8QARILCgdN", 
            "b25zdGVyEAISCwoHU29saWRlchADEgcKA05wYxAEKigKDVN1YkVudGl0eVR5", 
          "cGUSCgoGUGFzc2VyEAESCwoHUGVkZGxlchAC"));
      pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
        descriptor = root;
        return null;
      };
      pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
          new pbd::FileDescriptor[] {
          global::yd_fieldoptions.YdFieldoptions.Descriptor, 
          }, assigner);
    }
    #endregion
    
  }
  #region Enums
  public enum EntityType {
    Hero = 1,
    Monster = 2,
    Solider = 3,
    Npc = 4,
  }
  
  public enum SubEntityType {
    Passer = 1,
    Peddler = 2,
  }
  
  #endregion
  
}

#endregion Designer generated code
