// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto_config.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from proto_config.proto</summary>
  public static partial class ProtoConfigReflection {

    #region Descriptor
    /// <summary>File descriptor for proto_config.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoConfigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJwcm90b19jb25maWcucHJvdG8SCFByb3RvY29sKpYDCgpFbnRpdHlUeXBl",
            "EgkKBUVtcHR5EAASCAoESGVybxABEgoKBlBhc3NlchACEggKBEFyZWEQAxIL",
            "CgdGbHlJdGVtEAQSCQoFVGhpbmcQBRIKCgZMYWRkZXIQBhIJCgVHdWFyZBAH",
            "EggKBExpbmUQCBILCgdQZWRkbGVyEAkSCAoEQm9hdBAKEgsKB0JvbmZpcmUQ",
            "DBIICgRCb3NzEA0SCAoETmVzdBAOEggKBERyb3AQDxITCg9BbnRpZG90ZVNj",
            "YXR0ZXIQEBILCgdNb25zdGVyEBESCAoEVGFzaxASEg8KC0ZpcmVEaWFtb25k",
            "EBMSDAoISW5zYW5pdHkQFBIICgRCYWxsEBUSDQoJTWFnaWNXYWxsEBYSEAoM",
            "U2VhbGluZ1N3b3JkEBcSDgoKR29sZGVuVGlyZRAYEg4KCkdvbGRlbkJlbGwQ",
            "GRIJCgVBcnJvdxAaEgwKCEhpZGVBcmVhEBsSDwoLVGh1bmRlck5haWwQHBIQ",
            "CgxUaHVuZGVyRmllbGQQHRIQCgxBcmNoaXRlY3R1cmUQHio3Cg1GbHlFbnRp",
            "dHlUeXBlEgwKCEZseUVtcHR5EAASBwoDQm93EAESDwoLVGh1bmRlckxpbmUQ",
            "AiplChBDdXN0b21FbnRpdHlUeXBlEgwKCENFX0VtcHR5EAASCgoGQ0VfQm93",
            "EAESEgoOQ0VfVGh1bmRlckxpbmUQAhIOCgpDRV9GbHlSaW5nEAMSEwoPQ0Vf",
            "VGh1bmRlclNwZWFyEARiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.EntityType), typeof(global::Protocol.FlyEntityType), typeof(global::Protocol.CustomEntityType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum EntityType {
    /// <summary>
    ///空
    /// </summary>
    [pbr::OriginalName("Empty")] Empty = 0,
    /// <summary>
    ///玩家
    /// </summary>
    [pbr::OriginalName("Hero")] Hero = 1,
    /// <summary>
    ///路人npc
    /// </summary>
    [pbr::OriginalName("Passer")] Passer = 2,
    /// <summary>
    ///藏匿区
    /// </summary>
    [pbr::OriginalName("Area")] Area = 3,
    /// <summary>
    ///炸弹
    /// </summary>
    [pbr::OriginalName("FlyItem")] FlyItem = 4,
    /// <summary>
    ///物件
    /// </summary>
    [pbr::OriginalName("Thing")] Thing = 5,
    /// <summary>
    ///连接点
    /// </summary>
    [pbr::OriginalName("Ladder")] Ladder = 6,
    /// <summary>
    ///警卫npc
    /// </summary>
    [pbr::OriginalName("Guard")] Guard = 7,
    /// <summary>
    ///线
    /// </summary>
    [pbr::OriginalName("Line")] Line = 8,
    /// <summary>
    ///摊贩npc
    /// </summary>
    [pbr::OriginalName("Peddler")] Peddler = 9,
    /// <summary>
    ///简单移动NPC
    /// </summary>
    [pbr::OriginalName("Boat")] Boat = 10,
    /// <summary>
    ///篝火
    /// </summary>
    [pbr::OriginalName("Bonfire")] Bonfire = 12,
    /// <summary>
    ///Boss
    /// </summary>
    [pbr::OriginalName("Boss")] Boss = 13,
    /// <summary>
    ///巢穴
    /// </summary>
    [pbr::OriginalName("Nest")] Nest = 14,
    /// <summary>
    ///掉落物
    /// </summary>
    [pbr::OriginalName("Drop")] Drop = 15,
    /// <summary>
    ///解药散布
    /// </summary>
    [pbr::OriginalName("AntidoteScatter")] AntidoteScatter = 16,
    /// <summary>
    ///怪物
    /// </summary>
    [pbr::OriginalName("Monster")] Monster = 17,
    /// <summary>
    ///任务
    /// </summary>
    [pbr::OriginalName("Task")] Task = 18,
    /// <summary>
    ///炎玉
    /// </summary>
    [pbr::OriginalName("FireDiamond")] FireDiamond = 19,
    /// <summary>
    ///蛊灵
    /// </summary>
    [pbr::OriginalName("Insanity")] Insanity = 20,
    /// <summary>
    ///烟雾弹  球
    /// </summary>
    [pbr::OriginalName("Ball")] Ball = 21,
    /// <summary>
    ///升岩壁
    /// </summary>
    [pbr::OriginalName("MagicWall")] MagicWall = 22,
    /// <summary>
    ///封印剑
    /// </summary>
    [pbr::OriginalName("SealingSword")] SealingSword = 23,
    /// <summary>
    ///金轮
    /// </summary>
    [pbr::OriginalName("GoldenTire")] GoldenTire = 24,
    /// <summary>
    ///金钟罩
    /// </summary>
    [pbr::OriginalName("GoldenBell")] GoldenBell = 25,
    /// <summary>
    ///弓箭
    /// </summary>
    [pbr::OriginalName("Arrow")] Arrow = 26,
    /// <summary>
    ///藏匿区
    /// </summary>
    [pbr::OriginalName("HideArea")] HideArea = 27,
    /// <summary>
    ///雷钉
    /// </summary>
    [pbr::OriginalName("ThunderNail")] ThunderNail = 28,
    /// <summary>
    ///电浆
    /// </summary>
    [pbr::OriginalName("ThunderField")] ThunderField = 29,
    /// <summary>
    ///建筑
    /// </summary>
    [pbr::OriginalName("Architecture")] Architecture = 30,
  }

  public enum FlyEntityType {
    /// <summary>
    ///空
    /// </summary>
    [pbr::OriginalName("FlyEmpty")] FlyEmpty = 0,
    /// <summary>
    ///弓箭
    /// </summary>
    [pbr::OriginalName("Bow")] Bow = 1,
    /// <summary>
    ///雷斩剑气
    /// </summary>
    [pbr::OriginalName("ThunderLine")] ThunderLine = 2,
  }

  public enum CustomEntityType {
    [pbr::OriginalName("CE_Empty")] CeEmpty = 0,
    [pbr::OriginalName("CE_Bow")] CeBow = 1,
    [pbr::OriginalName("CE_ThunderLine")] CeThunderLine = 2,
    [pbr::OriginalName("CE_FlyRing")] CeFlyRing = 3,
    [pbr::OriginalName("CE_ThunderSpear")] CeThunderSpear = 4,
  }

  #endregion

}

#endregion Designer generated code
