// Generated by ProtoGen, Version=2.4.1.555, Culture=neutral, PublicKeyToken=17b3b1f090c3ea48.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace yd_fieldoptions {
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class YdFieldoptions {
  
    #region Extension registration
    public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
      registry.Add(global::yd_fieldoptions.YdFieldoptions.FieldType);
      registry.Add(global::yd_fieldoptions.YdFieldoptions.FieldStringLen);
      registry.Add(global::yd_fieldoptions.YdFieldoptions.FieldNotNull);
      registry.Add(global::yd_fieldoptions.YdFieldoptions.FieldAutoIncrement);
      registry.Add(global::yd_fieldoptions.YdFieldoptions.FieldTypename);
      registry.Add(global::yd_fieldoptions.YdFieldoptions.FieldArysize);
      registry.Add(global::yd_fieldoptions.YdFieldoptions.FieldBufsize);
      registry.Add(global::yd_fieldoptions.YdFieldoptions.FieldCname);
      registry.Add(global::yd_fieldoptions.YdFieldoptions.FieldSelectId);
      registry.Add(global::yd_fieldoptions.YdFieldoptions.FieldId);
      registry.Add(global::yd_fieldoptions.YdFieldoptions.FieldEnumCname);
    }
    #endregion
    #region Extensions
    public const int FieldTypeFieldNumber = 41000;
    public static pb::GeneratedExtensionBase<global::yd_fieldoptions.message_field_type> FieldType;
    public const int FieldStringLenFieldNumber = 41001;
    public static pb::GeneratedExtensionBase<int> FieldStringLen;
    public const int FieldNotNullFieldNumber = 41002;
    public static pb::GeneratedExtensionBase<bool> FieldNotNull;
    public const int FieldAutoIncrementFieldNumber = 40003;
    public static pb::GeneratedExtensionBase<bool> FieldAutoIncrement;
    public const int FieldTypenameFieldNumber = 42000;
    public static pb::GeneratedExtensionBase<string> FieldTypename;
    public const int FieldArysizeFieldNumber = 42001;
    public static pb::GeneratedExtensionBase<int> FieldArysize;
    public const int FieldBufsizeFieldNumber = 42002;
    public static pb::GeneratedExtensionBase<int> FieldBufsize;
    public const int FieldCnameFieldNumber = 43000;
    public static pb::GeneratedExtensionBase<string> FieldCname;
    public const int FieldSelectIdFieldNumber = 43001;
    public static pb::GeneratedExtensionBase<string> FieldSelectId;
    public const int FieldIdFieldNumber = 43002;
    public static pb::GeneratedExtensionBase<string> FieldId;
    public const int FieldEnumCnameFieldNumber = 2000;
    public static pb::GeneratedExtensionBase<string> FieldEnumCname;
    #endregion
    
    #region Static variables
    #endregion
    #region Descriptor
    public static pbd::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbd::FileDescriptor descriptor;
    
    static YdFieldoptions() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1pbmNsdWRlL3lkX2ZpZWxkb3B0aW9ucy5wcm90bxIPeWRfZmllbGRvcHRp", 
            "b25zGiBnb29nbGUvcHJvdG9idWYvZGVzY3JpcHRvci5wcm90bypfChJtZXNz", 
            "YWdlX2ZpZWxkX3R5cGUSFgoSRV9GSUVMRFRZUEVfTk9STUFMEAESGgoWRV9G", 
            "SUVMRFRZUEVfUFJJTUFSWUtFWRACEhUKEUVfRklFTERUWVBFX0lOREVYEAM6", 
            "dwoKZmllbGRfdHlwZRIdLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE9wdGlvbnMY", 
            "qMACIAEoDjIjLnlkX2ZpZWxkb3B0aW9ucy5tZXNzYWdlX2ZpZWxkX3R5cGU6", 
            "EkVfRklFTERUWVBFX05PUk1BTFIJZmllbGRUeXBlOkkKEGZpZWxkX3N0cmlu", 
            "Z19sZW4SHS5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25zGKnAAiABKAVS", 
            "DmZpZWxkU3RyaW5nTGVuOkwKDmZpZWxkX25vdF9udWxsEh0uZ29vZ2xlLnBy", 
            "b3RvYnVmLkZpZWxkT3B0aW9ucxiqwAIgASgIOgVmYWxzZVIMZmllbGROb3RO", 
            "dWxsOlgKFGZpZWxkX2F1dG9faW5jcmVtZW50Eh0uZ29vZ2xlLnByb3RvYnVm", 
            "LkZpZWxkT3B0aW9ucxjDuAIgASgIOgVmYWxzZVISZmllbGRBdXRvSW5jcmVt", 
            "ZW50OkYKDmZpZWxkX3R5cGVuYW1lEh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxk", 
            "T3B0aW9ucxiQyAIgASgJUg1maWVsZFR5cGVuYW1lOkQKDWZpZWxkX2FyeXNp", 
            "emUSHS5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25zGJHIAiABKAVSDGZp", 
            "ZWxkQXJ5c2l6ZTpECg1maWVsZF9idWZzaXplEh0uZ29vZ2xlLnByb3RvYnVm", 
            "LkZpZWxkT3B0aW9ucxiSyAIgASgFUgxmaWVsZEJ1ZnNpemU6QAoLZmllbGRf", 
            "Y25hbWUSHS5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25zGPjPAiABKAlS", 
            "CmZpZWxkQ25hbWU6RwoPZmllbGRfc2VsZWN0X2lkEh0uZ29vZ2xlLnByb3Rv", 
            "YnVmLkZpZWxkT3B0aW9ucxj5zwIgASgJUg1maWVsZFNlbGVjdElkOjoKCGZp", 
            "ZWxkX2lkEh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucxj6zwIgASgJ", 
            "UgdmaWVsZElkOkwKEGZpZWxkX2VudW1fY25hbWUSIS5nb29nbGUucHJvdG9i", 
          "dWYuRW51bVZhbHVlT3B0aW9ucxjQDyABKAlSDmZpZWxkRW51bUNuYW1l"));
      pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
        descriptor = root;
        global::yd_fieldoptions.YdFieldoptions.FieldType = pb::GeneratedSingleExtension<global::yd_fieldoptions.message_field_type>.CreateInstance(global::yd_fieldoptions.YdFieldoptions.Descriptor.Extensions[0]);
        global::yd_fieldoptions.YdFieldoptions.FieldStringLen = pb::GeneratedSingleExtension<int>.CreateInstance(global::yd_fieldoptions.YdFieldoptions.Descriptor.Extensions[1]);
        global::yd_fieldoptions.YdFieldoptions.FieldNotNull = pb::GeneratedSingleExtension<bool>.CreateInstance(global::yd_fieldoptions.YdFieldoptions.Descriptor.Extensions[2]);
        global::yd_fieldoptions.YdFieldoptions.FieldAutoIncrement = pb::GeneratedSingleExtension<bool>.CreateInstance(global::yd_fieldoptions.YdFieldoptions.Descriptor.Extensions[3]);
        global::yd_fieldoptions.YdFieldoptions.FieldTypename = pb::GeneratedSingleExtension<string>.CreateInstance(global::yd_fieldoptions.YdFieldoptions.Descriptor.Extensions[4]);
        global::yd_fieldoptions.YdFieldoptions.FieldArysize = pb::GeneratedSingleExtension<int>.CreateInstance(global::yd_fieldoptions.YdFieldoptions.Descriptor.Extensions[5]);
        global::yd_fieldoptions.YdFieldoptions.FieldBufsize = pb::GeneratedSingleExtension<int>.CreateInstance(global::yd_fieldoptions.YdFieldoptions.Descriptor.Extensions[6]);
        global::yd_fieldoptions.YdFieldoptions.FieldCname = pb::GeneratedSingleExtension<string>.CreateInstance(global::yd_fieldoptions.YdFieldoptions.Descriptor.Extensions[7]);
        global::yd_fieldoptions.YdFieldoptions.FieldSelectId = pb::GeneratedSingleExtension<string>.CreateInstance(global::yd_fieldoptions.YdFieldoptions.Descriptor.Extensions[8]);
        global::yd_fieldoptions.YdFieldoptions.FieldId = pb::GeneratedSingleExtension<string>.CreateInstance(global::yd_fieldoptions.YdFieldoptions.Descriptor.Extensions[9]);
        global::yd_fieldoptions.YdFieldoptions.FieldEnumCname = pb::GeneratedSingleExtension<string>.CreateInstance(global::yd_fieldoptions.YdFieldoptions.Descriptor.Extensions[10]);
        pb::ExtensionRegistry registry = pb::ExtensionRegistry.CreateInstance();
        RegisterAllExtensions(registry);
        global::Google.ProtocolBuffers.DescriptorProtos.DescriptorProtoFile.RegisterAllExtensions(registry);
        return registry;
      };
      pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
          new pbd::FileDescriptor[] {
          global::Google.ProtocolBuffers.DescriptorProtos.DescriptorProtoFile.Descriptor, 
          }, assigner);
    }
    #endregion
    
  }
  #region Enums
  public enum message_field_type {
    E_FIELDTYPE_NORMAL = 1,
    E_FIELDTYPE_PRIMARYKEY = 2,
    E_FIELDTYPE_INDEX = 3,
  }
  
  #endregion
  
}

#endregion Designer generated code
